Repository giselles-ai/giselle, pull requests merged in 2024-11, with the labels that each got.

#68 Prototype flow
  app/(playground)/p/[agentId]/beta-proto/artifact/render.tsx
  app/(playground)/p/[agentId]/beta-proto/artifact/types.ts
  app/(playground)/p/[agentId]/beta-proto/flow/action.ts
  app/(playground)/p/[agentId]/beta-proto/flow/components/run-button.tsx
  app/(playground)/p/[agentId]/beta-proto/flow/composite-actions.ts
  app/(playground)/p/[agentId]/beta-proto/flow/server-action.ts
  app/(playground)/p/[agentId]/beta-proto/flow/server-actions/generate-text.ts
  app/(playground)/p/[agentId]/beta-proto/flow/server-actions/websearch.ts
  app/(playground)/p/[agentId]/beta-proto/flow/source/types.ts
  app/(playground)/p/[agentId]/beta-proto/flow/source/utils.ts
  app/(playground)/p/[agentId]/beta-proto/flow/types.ts
  app/(playground)/p/[agentId]/beta-proto/flow/utils.ts
  app/(playground)/p/[agentId]/beta-proto/giselle-node/types.ts
  app/(playground)/p/[agentId]/beta-proto/giselle-node/utils.ts
  app/(playground)/p/[agentId]/beta-proto/graph/actions.ts
  app/(playground)/p/[agentId]/beta-proto/graph/reducer.ts
  app/(playground)/p/[agentId]/beta-proto/graph/types.ts
  app/(playground)/p/[agentId]/beta-proto/source/types.ts
  app/(playground)/p/[agentId]/beta-proto/source/utils.ts
  app/(playground)/p/[agentId]/beta-proto/viewer.tsx
  app/(playground)/p/[agentId]/beta-proto/viewer/components/step-item.tsx
  app/(playground)/p/[agentId]/beta-proto/web-search/server-action.ts
  app/(playground)/p/[agentId]/page.tsx
  services/agents/actions/create-agent.ts
Labels: private-beta

#74 feat: Set 5-minute timeout for Agent playground page
  app/(playground)/p/[agentId]/page.tsx
  vercel.json
Labels: enhancement

#77 Add model selection option to Text Generator node with Claude support
  .env.example
  app/(playground)/p/[agentId]/beta-proto/feature-flags/types.ts
  app/(playground)/p/[agentId]/beta-proto/flow/server-action.ts
  app/(playground)/p/[agentId]/beta-proto/flow/server-actions/generate-text.ts
  app/(playground)/p/[agentId]/beta-proto/flow/step-nodes/types.ts
  app/(playground)/p/[agentId]/beta-proto/flow/step-nodes/utils.ts
  app/(playground)/p/[agentId]/beta-proto/flow/types.ts
  app/(playground)/p/[agentId]/beta-proto/flow/utils.ts
  app/(playground)/p/[agentId]/beta-proto/giselle-node/components/panel/text-generator.tsx
  app/(playground)/p/[agentId]/beta-proto/viewer.tsx
  app/(playground)/p/[agentId]/beta-proto/viewer/components/step-item.tsx
  app/(playground)/p/[agentId]/page.tsx
  bun.lockb
  flags.ts
  package.json
  services/agents/nodes/classes/agent/invoke-agent.ts
  services/agents/nodes/classes/text/build-template.ts
Labels: private-beta

#78 feat(llm): Add configurable model provider support
  app/(playground)/p/[agentId]/beta-proto/artifact/server-actions.ts
  app/(playground)/p/[agentId]/beta-proto/artifact/types.ts
  app/(playground)/p/[agentId]/beta-proto/artifact/utils.ts
  app/(playground)/p/[agentId]/beta-proto/graph/actions.ts
Labels: private-beta

#80 [docs] Replaced route06inc with giselles-ai due to a GitHub organization transfer.
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
  SECURITY.md
  config/dependency_decisions.yml
  docs/packages-license.md
Labels: documentation

#81 Enhance AI Model Control with Temperature and Top-P Parameters
  app/(playground)/p/[agentId]/beta-proto/artifact/server-actions.ts
  app/(playground)/p/[agentId]/beta-proto/components/slider.tsx
  app/(playground)/p/[agentId]/beta-proto/flow/server-actions/generate-text.ts
  app/(playground)/p/[agentId]/beta-proto/giselle-node/components/panel/temperature-slider.tsx
  app/(playground)/p/[agentId]/beta-proto/giselle-node/components/panel/text-generator.tsx
  app/(playground)/p/[agentId]/beta-proto/giselle-node/components/panel/top-p-slider.tsx
  bun.lockb
  package.json
Labels: enhancement

#86 [feat] Implement agent name management system with UI enhancements
  app/(playground)/p/[agentId]/beta-proto/component.tsx
  app/(playground)/p/[agentId]/beta-proto/components/icons/layers.tsx
  app/(playground)/p/[agentId]/beta-proto/contexts/agent-name.tsx
  app/(playground)/p/[agentId]/beta-proto/editor.tsx
  app/(playground)/p/[agentId]/beta-proto/left-menu/components/tabs.tsx
  app/(playground)/p/[agentId]/beta-proto/left-menu/left-menu.tsx
  app/(playground)/p/[agentId]/beta-proto/left-menu/overview/overview.tsx
  app/(playground)/p/[agentId]/beta-proto/left-menu/overview/server-actions.ts
  app/(playground)/p/[agentId]/page.tsx
Labels: enhancement

#85 Keep Vercel Function awake during telemetry exporting interval
  app/(playground)/p/[agentId]/beta-proto/artifact/server-actions.ts
  bun.lockb
  docs/packages-license.md
  instrumentation.node.ts
  instrumentation.ts
  lib/opentelemetry/base.ts
  lib/opentelemetry/index.ts
  lib/opentelemetry/log.ts
  lib/opentelemetry/metric.ts
  lib/opentelemetry/trace.ts
  package.json
  sentry.server.config.ts
Labels: enhancement

#89 [feat] Implement GitHub integration configuration UI with workflow automation
  app/(playground)/p/[agentId]/beta-proto/components/label.tsx
  app/(playground)/p/[agentId]/beta-proto/components/select.tsx
  app/(playground)/p/[agentId]/beta-proto/feature-flags/types.ts
  app/(playground)/p/[agentId]/beta-proto/left-menu/components/section.tsx
  app/(playground)/p/[agentId]/beta-proto/left-menu/github-integration/github-integration.tsx
  app/(playground)/p/[agentId]/beta-proto/left-menu/left-menu.tsx
  app/(playground)/p/[agentId]/page.tsx
Labels: private-beta

#90 Implement fetching GitHub repositories
  app/(playground)/p/[agentId]/beta-proto/component.tsx
  app/(playground)/p/[agentId]/beta-proto/github-integration/context.ts
  app/(playground)/p/[agentId]/beta-proto/github-integration/provider.tsx
  app/(playground)/p/[agentId]/beta-proto/left-menu/github-integration/github-integration.tsx
  app/(playground)/p/[agentId]/page.tsx
  services/external/github/user-client.ts
Labels: enhancement

#106 [feat] Implement GitHub Integration System with Webhook Support
  app/(playground)/p/[agentId]/beta-proto/component.tsx
  app/(playground)/p/[agentId]/beta-proto/flow/server-actions/generate-text.ts
  app/(playground)/p/[agentId]/beta-proto/flow/server-actions/websearch.ts
  app/(playground)/p/[agentId]/beta-proto/flow/utils.test.ts
  app/(playground)/p/[agentId]/beta-proto/flow/utils.ts
  app/(playground)/p/[agentId]/beta-proto/github-integration/context.ts
  app/(playground)/p/[agentId]/beta-proto/github-integration/provider.tsx
  app/(playground)/p/[agentId]/beta-proto/github-integration/types.ts
  app/(playground)/p/[agentId]/beta-proto/github-integration/utils.ts
  app/(playground)/p/[agentId]/beta-proto/left-menu/github-integration/github-integration.tsx
  app/(playground)/p/[agentId]/beta-proto/left-menu/github-integration/server-actions.ts
  app/(playground)/p/[agentId]/beta-proto/left-menu/overview/overview.tsx
  app/(playground)/p/[agentId]/page.tsx
  app/webhooks/github/command.test.ts
  app/webhooks/github/command.ts
  app/webhooks/github/route.ts
  drizzle/schema.ts
  migrations/0006_demonic_morlocks.sql
  migrations/0007_breezy_bromley.sql
  migrations/0008_cloudy_squadron_supreme.sql
  migrations/meta/0006_snapshot.json
  migrations/meta/0007_snapshot.json
  migrations/meta/0008_snapshot.json
  migrations/meta/_journal.json
  services/external/github/types.ts
Labels: private-beta

#108 feat: make call sign input controlled and update preview dynamically
  app/(playground)/p/[agentId]/beta-proto/left-menu/github-integration/github-integration.tsx
Labels: enhancement

#109 refactor(webhook): Extract GitHub workflow logic into separate function
  app/webhooks/github/route.ts
Labels: enhancement

#122 Add team tab in settings
  .env.example
  app/(main)/settings/layout.tsx
  app/(main)/settings/team/page.tsx
  flags.ts
Labels: enhancement

#127 Add team name edit functionality in settings
  app/(main)/settings/team/actions.ts
  app/(main)/settings/team/page.tsx
  app/(main)/settings/team/team-name-form.tsx
  app/(main)/settings/team/team-name.tsx
Labels: enhancement

#134 Skip checking subscription if freePlanFlag is enabled
  middleware.ts
Labels: enhancement, private-beta

#117 Create `security.txt` and add a GH Actions workflow to remind you of its updates
  .github/workflows/create_issue_security_txt.yml
  .github/workflows/templates/create_issue_security_txt.md
  public/.well-known/security.txt
Labels: enhancement

#129 feat: Restructure Playground node architecture for article creation workflow
  .env.example
  app/(playground)/p/[agentId]/beta-proto/components/icons/circle-plus.tsx
  app/(playground)/p/[agentId]/beta-proto/components/icons/panel-open.tsx
  app/(playground)/p/[agentId]/beta-proto/editor.tsx
  app/(playground)/p/[agentId]/beta-proto/feature-flags/types.ts
  app/(playground)/p/[agentId]/beta-proto/giselle-node/components/panel/text-generator.tsx
  app/(playground)/p/[agentId]/beta-proto/giselle-node/types.ts
  app/(playground)/p/[agentId]/canary/actions.ts
  app/(playground)/p/[agentId]/canary/components/bg.png
  app/(playground)/p/[agentId]/canary/components/block.tsx
  app/(playground)/p/[agentId]/canary/components/content-type-icon.tsx
  app/(playground)/p/[agentId]/canary/components/edge.tsx
  app/(playground)/p/[agentId]/canary/components/editor.tsx
  app/(playground)/p/[agentId]/canary/components/node-block.tsx
  app/(playground)/p/[agentId]/canary/components/node.tsx
  app/(playground)/p/[agentId]/canary/components/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/components/select.tsx
  app/(playground)/p/[agentId]/canary/components/slider.tsx
  app/(playground)/p/[agentId]/canary/contexts/graph.tsx
  app/(playground)/p/[agentId]/canary/contexts/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/mockData.json
  app/(playground)/p/[agentId]/canary/mockData.ts
  app/(playground)/p/[agentId]/canary/page.tsx
  app/(playground)/p/[agentId]/canary/prompts.ts
  app/(playground)/p/[agentId]/canary/types.ts
  app/(playground)/p/[agentId]/canary/utils.ts
  app/(playground)/p/[agentId]/page.tsx
  bun.lockb
  flags.ts
  package.json
Labels: private-beta
