Repository giselles-ai/giselle, pull requests merged in 2024-12, with the labels that each got.

#147 [refactor] Overhaul editor and toolbar with improved interaction model
  app/(playground)/p/[agentId]/canary/actions.ts
  app/(playground)/p/[agentId]/canary/components/dropdown-menu.tsx
  app/(playground)/p/[agentId]/canary/components/editor.tsx
  app/(playground)/p/[agentId]/canary/components/node.tsx
  app/(playground)/p/[agentId]/canary/components/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/components/toolbar.tsx
  app/(playground)/p/[agentId]/canary/constants.ts
  app/(playground)/p/[agentId]/canary/contexts/graph.tsx
  app/(playground)/p/[agentId]/canary/contexts/mouse-position.tsx
  app/(playground)/p/[agentId]/canary/contexts/toolbar.tsx
  app/(playground)/p/[agentId]/canary/mockData.ts
  app/(playground)/p/[agentId]/canary/types.ts
  app/(playground)/p/[agentId]/canary/utils.ts
  app/api/files/upload/route.ts
  app/globals.css
  bun.lockb
  package.json
Labels: private-beta

#148 Update schema and add migrations
  drizzle/schema.ts
  migrations/0011_thin_ink.sql
  migrations/meta/0011_snapshot.json
  migrations/meta/_journal.json
Labels: enhancement

#124 Enable to identify internal team
  app/(auth)/auth/callback/[provider]/route.ts
  app/(auth)/signup/verify-email/verify-email.ts
  drizzle/schema.ts
  migrations/0012_military_talisman.sql
  migrations/meta/0012_snapshot.json
  migrations/meta/_journal.json
  scripts/20241126-db-patch-teams-is-internal-team.ts
  services/accounts/actions/initialize-account.ts
Labels: enhancement

#149 [feat] Add Playground V2 with feature flag and schema updates
  app/(main)/agents/page.tsx
  app/(main)/agents/v2.tsx
  app/(playground)/p/[agentId]/page.tsx
  drizzle/schema.ts
  migrations/0013_nosy_whiplash.sql
  migrations/meta/0013_snapshot.json
  migrations/meta/_journal.json
Labels: private-beta

#136 Create new team with pro plan subscription
  .env.example
  app/(main)/layout.tsx
  app/webhooks/stripe/route.ts
  components/ui/radio-group.tsx
  docs/packages-license.md
  flags.ts
  package.json
  services/external/stripe/actions/upsert-subscription.ts
  services/teams/actions/create-team.ts
  services/teams/components/team-creation-form.tsx
  services/teams/components/team-creation-modal.tsx
  services/teams/constants.ts
Labels: enhancement

#152 [feat] Implement versioned graph persistence with UI improvements
  app/(main)/agents/v2.tsx
  app/(playground)/p/[agentId]/canary/actions.ts
  app/(playground)/p/[agentId]/canary/components/editor.tsx
  app/(playground)/p/[agentId]/canary/components/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/contexts/graph.tsx
  app/(playground)/p/[agentId]/canary/contexts/mouse-position.tsx
  app/(playground)/p/[agentId]/canary/contexts/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/contexts/toolbar.tsx
  app/(playground)/p/[agentId]/canary/page.tsx
  app/(playground)/p/[agentId]/canary/utils.test.ts
  app/(playground)/p/[agentId]/canary/utils.ts
Labels: private-beta

#153 Fetch pro plan price from stripe
  services/external/stripe/index.ts
  services/external/stripe/utils.ts
  services/teams/components/team-creation-form.tsx
  services/teams/components/team-creation-modal.tsx
Labels: enhancement

#154 [feat] Implement node deletion with cascade cleanup and edge protection
  app/(playground)/p/[agentId]/canary/components/editor.tsx
  app/(playground)/p/[agentId]/canary/contexts/graph.tsx
Labels: private-beta

#145 Manage billing for existing team
  app/(main)/settings/layout.tsx
  app/(main)/settings/team/billing-section.tsx
  app/(main)/settings/team/page.tsx
  docs/packages-license.md
  services/external/stripe/actions/upsert-subscription.ts
  services/teams/actions/create-checkout-session.ts
  services/teams/actions/create-team.ts
  services/teams/actions/manage-billing.ts
  services/teams/actions/upgrade-team.ts
  services/teams/constants.ts
Labels: enhancement

#144 Add display name and email management to account settings page
  app/(main)/settings/account/account-display-name-form.tsx
  app/(main)/settings/account/actions.ts
  app/(main)/settings/account/page.tsx
  scripts/20241129-db-patch-add-name-and-email-to-users.ts
  services/accounts/actions/initialize-account.ts
Labels: enhancement

#155 [feat] Add text generation monitoring, UI improvements and prompt handling
  app/(playground)/p/[agentId]/canary/actions.ts
  app/(playground)/p/[agentId]/canary/components/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/contexts/graph.tsx
  app/(playground)/p/[agentId]/canary/prompts.test.ts
  app/(playground)/p/[agentId]/canary/prompts.ts
  app/(playground)/p/[agentId]/canary/utils.ts
Labels: private-beta

#112 Add event capturing into PostHog
  app/layout.tsx
  app/posthog-page-view.tsx
  app/providers.tsx
  bun.lockb
  docs/packages-license.md
  package.json
Labels: enhancement

#158 [feat] Auto-open properties panel on node selection
  app/(playground)/p/[agentId]/canary/components/editor.tsx
Labels: private-beta

#159 feat(ui): Add keyboard shortcuts for toolbar actions
  app/(playground)/p/[agentId]/canary/components/editor.tsx
  app/(playground)/p/[agentId]/canary/components/keyboard-shortcut.tsx
  app/(playground)/p/[agentId]/canary/components/toolbar.tsx
Labels: private-beta

#161 [feat] Add navigation panel with editable agent name
  app/(playground)/p/[agentId]/canary/components/editor.tsx
  app/(playground)/p/[agentId]/canary/components/navigation-panel.tsx
  app/(playground)/p/[agentId]/canary/contexts/agent-name.tsx
  app/(playground)/p/[agentId]/canary/page.tsx
Labels: private-beta

#162 fix(shortcuts): Prevent keyboard shortcuts in form inputs
  app/(playground)/p/[agentId]/canary/components/keyboard-shortcut.tsx
Labels: private-beta

#164 [feat] Modernize agent management UI with new layout and loading states
  app/(main)/agents-v2/layout.tsx
  app/(main)/agents-v2/page.tsx
  app/(main)/agents/page.tsx
  app/(main)/agents/v2.tsx
  app/(playground)/p/[agentId]/canary/components/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/utils.ts
Labels: private-beta

#167 feat(canary): Add support for file source in actions
  app/(playground)/p/[agentId]/canary/actions.ts
  app/(playground)/p/[agentId]/canary/prompts.ts
Labels: private-beta

#163 Add select team function
  .env.example
  app/(auth)/lib/get-current-measurement-scope.ts
  app/(auth)/lib/get-current-team.ts
  app/(auth)/lib/index.ts
  app/(main)/agents-v2/layout.tsx
  app/(main)/agents-v2/page.tsx
  app/(main)/agents/page.tsx
  app/(main)/layout.tsx
  app/(main)/settings/team/actions.ts
  app/(main)/settings/team/billing-section.tsx
  app/(main)/settings/team/team-name-form.tsx
  app/(main)/settings/team/team-name.tsx
  app/(playground)/p/[agentId]/beta-proto/left-menu/overview/server-actions.ts
  app/subscriptions/success/route.ts
  lib/giselle-session.ts
  lib/signed-cookie.test.ts
  lib/signed-cookie.ts
  services/accounts/actions/retrieve-stripe-subscription.ts
  services/agents/actions/create-agent.ts
  services/agents/actions/get-agent.ts
  services/agents/actions/set-agent-name.ts
  services/teams/actions/create-checkout-session.ts
  services/teams/actions/create-team.ts
  services/teams/actions/select-team.ts
  services/teams/actions/upgrade-team.ts
  services/teams/components/team-creation-form.tsx
  services/teams/components/team-creation-modal.tsx
  services/teams/components/team-creation.tsx
  services/teams/components/team-selection-form.tsx
  services/teams/components/team-selection.tsx
  services/teams/fetch-current-team.ts
  services/teams/fetch-user-teams.ts
  services/teams/index.ts
  services/teams/set-current-team.ts
Labels: enhancement, private-beta

#176 Add agents.creator_db_id
  app/(main)/agents-v2/layout.tsx
  app/(main)/agents/page.tsx
  drizzle/schema.ts
  migrations/0014_lucky_sabretooth.sql
  migrations/meta/0014_snapshot.json
  migrations/meta/_journal.json
  services/accounts/fetch-current-user.ts
  services/accounts/index.ts
  services/agents/actions/create-agent.ts
Labels: enhancement

#180 [feat] Add developer mode and enhance error handling system
  .env.example
  app/(playground)/p/[agentId]/canary/actions.ts
  app/(playground)/p/[agentId]/canary/components/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/contexts/developer-mode.tsx
  app/(playground)/p/[agentId]/canary/contexts/execution.tsx
  app/(playground)/p/[agentId]/canary/contexts/graph.tsx
  app/(playground)/p/[agentId]/canary/page.tsx
  app/(playground)/p/[agentId]/canary/utils.ts
  flags.ts
Labels: private-beta

#174 Enable capture PostHog Pageleave event
  app/providers.tsx
Labels: enhancement

#182 feat(playground): Add customizable system prompt for text generation
  app/(playground)/p/[agentId]/canary/actions.ts
  app/(playground)/p/[agentId]/canary/components/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/prompts.ts
  app/(playground)/p/[agentId]/canary/types.ts
Labels: private-beta

#160 feat: Add team members list
  app/(main)/settings/team/actions.ts
  app/(main)/settings/team/team-members-list.tsx
  app/(main)/settings/team/team-members.tsx
Labels: private-beta

#193 [feat] Implement graph versioning and subgraph organization system
  app/(playground)/p/[agentId]/canary/components/navigation-panel.tsx
  app/(playground)/p/[agentId]/canary/graph.test.ts
  app/(playground)/p/[agentId]/canary/graph.ts
  app/(playground)/p/[agentId]/canary/page.tsx
  app/(playground)/p/[agentId]/canary/types.ts
  app/(playground)/p/[agentId]/canary/utils.ts
Labels: private-beta

#228 [feat] Implement graph execution engine with real-time tracking and viewer UI
  app/(main)/agents-v2/layout.tsx
  app/(main)/agents-v2/page.tsx
  app/(playground)/p/[agentId]/canary/actions.ts
  app/(playground)/p/[agentId]/canary/components/editor.tsx
  app/(playground)/p/[agentId]/canary/components/header.tsx
  app/(playground)/p/[agentId]/canary/components/icons/sparkles.tsx
  app/(playground)/p/[agentId]/canary/components/navigation-panel.tsx
  app/(playground)/p/[agentId]/canary/components/playground.tsx
  app/(playground)/p/[agentId]/canary/components/properties-panel.tsx
  app/(playground)/p/[agentId]/canary/components/ui/button.tsx
  app/(playground)/p/[agentId]/canary/components/ui/empty-state.tsx
  app/(playground)/p/[agentId]/canary/components/viewer.tsx
  app/(playground)/p/[agentId]/canary/contexts/execution.tsx
  app/(playground)/p/[agentId]/canary/contexts/graph.tsx
  app/(playground)/p/[agentId]/canary/contexts/playground-mode.tsx
  app/(playground)/p/[agentId]/canary/graph.ts
  app/(playground)/p/[agentId]/canary/lib/execution.ts
  app/(playground)/p/[agentId]/canary/lib/graph.test.ts
  app/(playground)/p/[agentId]/canary/lib/graph.ts
  app/(playground)/p/[agentId]/canary/lib/prompts.test.ts
  app/(playground)/p/[agentId]/canary/lib/prompts.ts
  app/(playground)/p/[agentId]/canary/lib/utils.test.ts
  app/(playground)/p/[agentId]/canary/lib/utils.ts
  app/(playground)/p/[agentId]/canary/page.tsx
  app/(playground)/p/[agentId]/canary/types.ts
Labels: private-beta

#239 [feat] Enhance execution tracing with multi-level telemetry capture
  app/(playground)/p/[agentId]/canary/lib/execution.ts
Labels: enhancement

#271 [DO NOT MERGE UNTIL 2024/12/26] Activate free plan
  app/(auth)/login/page.tsx
  app/(main)/settings/layout.tsx
  flags.ts
  services/agents/activities/constants.ts
Labels: enhancement
