Repository giselles-ai/giselle, pull requests merged in 2025-06, with the labels that each got.

#1020 Refactor generation storage paths
  packages/giselle-engine/src/core/generations/utils.test.ts
  packages/giselle-engine/src/core/generations/utils.ts
Labels: codex

#1033 Add GitHub PR review comment reply action
  packages/flow/src/action/github.ts
  packages/giselle-engine/src/core/operations/execute-action.ts
  packages/github-tool/src/pull-requests.ts
Labels: codex

#1038 Remove flowNode and runV2 feature flags
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  packages/workspace/src/react/feature-flag.ts
  packages/workspace/src/react/workspace.tsx
Labels: codex

#1043 Remove web page node flag
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  packages/workspace/src/react/feature-flag.ts
  packages/workspace/src/react/workspace.tsx
Labels: codex

#1046 Add action result panel
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/generation-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/github-action-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/index.tsx
Labels: codex

#1058 Update run button styling and hide when no start nodes
  internal-packages/workflow-designer-ui/src/header/run-button/run-button.tsx
Labels: Review effort 2/5

#1060 Refactor Generation schema to use discriminated union for improved type safety
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/generation-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/generation-panel.tsx
  internal-packages/workflow-designer-ui/src/ui/generation-view.tsx
  packages/data-type/src/generation/index.ts
  packages/giselle-engine/src/core/generations/internal/set-generation.ts
  packages/giselle-engine/src/react/generations/contexts/generation-runner-system.tsx
Labels: Review effort 2/5

#1061 refactor(data-type): simplify generation schema structure
  packages/data-type/src/generation/index.ts
Labels: Review effort 2/5

#1051 Fix trigger node duplication to preserve settings configuration
  packages/node-utils/src/node-factories.ts
  packages/workflow-designer/src/react/workflow-designer-context.tsx
Labels: Review effort 2/5

#1062 Implement GitHub progress comments
  packages/giselle-engine/src/core/flows/run-flow.ts
  packages/giselle-engine/src/core/github/event-handlers.test.ts
  packages/giselle-engine/src/core/github/event-handlers.ts
  packages/giselle-engine/src/core/github/handle-webhook-v2.ts
  packages/github-tool/src/issues.ts
  packages/github-tool/src/pull-requests.ts
Labels: codex, Review effort 3/5

#1076 Bump @supabase/* to latest version in /apps/studio.giselles.ai
  apps/studio.giselles.ai/package.json
  pnpm-lock.yaml
Labels: dependencies, Review effort 2/5

#1078 sidemenu(feature flag)
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/playground/app/workspaces/[workspaceId]/page.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/run-button/index.ts
  internal-packages/workflow-designer-ui/src/editor/run-button/run-button.tsx
  internal-packages/workflow-designer-ui/src/editor/run-button/ui/button.tsx
  internal-packages/workflow-designer-ui/src/editor/side-menu/index.ts
  internal-packages/workflow-designer-ui/src/editor/side-menu/side-menu.tsx
  internal-packages/workflow-designer-ui/src/workflow-designer-ui.css
  packages/workspace/src/react/feature-flag.ts
  packages/workspace/src/react/workspace.tsx
Labels: Review effort 3/5

#1084 fix: use structuredClone for action state to prevent shared mutable state
  packages/workflow-designer/src/react/workflow-designer-context.tsx
Labels: Review effort 2/5

#1083 Add size prop to EditableText component
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/editable-text.tsx
  internal-packages/workflow-designer-ui/src/editor/side-menu/side-menu.tsx
Labels: Review effort 2/5

#1085 feat: implement vector store node duplication with settings preservation
  packages/node-utils/src/node-factories.ts
  packages/workflow-designer/src/react/workflow-designer-context.tsx
Labels: Review effort 2/5

#1086 refactor: migrate from Beta context to unified feature flag system
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/playground/app/workspaces/[workspaceId]/page.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/page.client.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/page.tsx
  internal-packages/workflow-designer-ui/src/editor/beta.ts
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  packages/workspace/src/react/feature-flag.ts
  packages/workspace/src/react/workspace.tsx
Labels: Review effort 3/5

#1089 Fix VectorStore node duplication settings preservation
  packages/workflow-designer/src/react/workflow-designer-context.tsx
Labels: Review effort 2/5

#1087 feat: implement tabbed navigation in workflow designer
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/side-menu/side-menu.tsx
Labels: Review effort 2/5

#1088 Add searchPullRequests to github-tool
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/github-tools.tsx
  packages/github-tool/src/tools.ts
Labels: codex, Review effort 2/5

#1090 Add sidemenu tools panel for text generation nodes
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tools-panel.tsx
Labels: Review effort 3/5

#1097 Update price of OpenAI o3
  packages/language-model/src/costs/model-prices.ts
Labels: Review effort 2/5

#1095 Fix TailwindCSS IntelliSense in workflow-designer-ui package
  apps/playground/app/globals.css
  apps/playground/package.json
  apps/studio.giselles.ai/app/globals.css
  internal-packages/workflow-designer-ui/package.json
  internal-packages/workflow-designer-ui/src/app/globals.css
  pnpm-lock.yaml
Labels: Review effort 2/5

#1100 fix: add workaround for Tailwind CSS IntelliSense issue in workflow-designer-ui
  internal-packages/workflow-designer-ui/src/app/workaround.css
Labels: Review effort 1/5

#1108 fix: GitHub Search API deprecation warnings
  packages/github-tool/src/tools.ts
Labels: Review effort 1/5

#1112 Upgrade Tailwind CSS to 4.1.10 and improve UI styling
  docs/packages-license.md
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tools-panel.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 2/5

#1111 Update Gemini 2.5 Pro Preview model from `gemini-2.5-pro-preview-05-06` to `gemini-2.5-pro-preview-06-05`
  packages/language-model/src/costs/model-prices.ts
  packages/language-model/src/google.test.ts
  packages/language-model/src/google.ts
  packages/workflow-utils/src/test/test-data.ts
Labels: codex, Review effort 2/5

#1116 feat: GitHub tool integration with workspace-scoped secret management
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tools-panel.tsx
  packages/data-type/src/index.ts
  packages/data-type/src/node/operations/text-generation.ts
  packages/data-type/src/secret/index.ts
  packages/data-type/src/workspace/id.ts
  packages/data-type/src/workspace/index.ts
  packages/giselle-engine/src/core/generations/generate-text.ts
  packages/giselle-engine/src/core/index.ts
  packages/giselle-engine/src/core/secrets/add-secret.ts
  packages/giselle-engine/src/core/secrets/decrypt-secret.ts
  packages/giselle-engine/src/core/secrets/index.ts
  packages/giselle-engine/src/core/secrets/paths.ts
  packages/giselle-engine/src/http/router.ts
  packages/workflow-designer/src/react/workflow-designer-context.tsx
Labels: Review effort 4/5

#1117 Enable web search action in workspace layout
  internal-packages/workflow-designer-ui/src/icons/node/index.tsx
Labels: Review effort 2/5

#1104 Add web-search action node support (Phase 1)
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/github-action-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  internal-packages/workflow-designer-ui/src/icons/node/index.tsx
  packages/data-type/src/node/operations/action.ts
  packages/flow/src/action/index.ts
  packages/flow/src/action/web-search.ts
  packages/giselle-engine/src/core/operations/execute-action.ts
  packages/node-utils/src/default-name.ts
  packages/workflow-designer/src/react/workflow-designer-context.tsx
  packages/workspace/src/react/feature-flag.ts
  packages/workspace/src/react/workspace.tsx
Labels: claude-code

#1124 Add GitHub Tool Integration UI to Workflow Designer
  internal-packages/workflow-designer-ui/src/app/globals.css
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tools-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/button.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/dialog.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/dropdown-menu.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/tabs.tsx
Labels: Review effort 3/5

#1123 Consolidate keyboard shortcuts and fix browser conflicts
  internal-packages/workflow-designer-ui/src/editor/components/keyboard-shortcuts.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/keyboard-shortcuts.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/keyboard-shortcuts.tsx
Labels: Review effort 2/5

#1126 Standardize telemetry format script to use biome check --write
  packages/telemetry/package.json
Labels: Review effort 1/5

#1120 fix(e2e): stabilize login test by waiting for navigation and checking for login errors
  apps/studio.giselles.ai/tests/e2e/login.spec.ts
Labels: Review effort 2/5

#1125 Simplify storage handling in telemetry and generation callbacks
  apps/playground/giselle-engine.ts
  apps/studio.giselles.ai/app/giselle-engine.ts
  packages/giselle-engine/src/core/generations/internal/use-generation-executor.ts
  packages/telemetry/package.json
  packages/telemetry/src/index.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#1110 Trace image generation
  apps/playground/giselle-engine.ts
  apps/studio.giselles.ai/app/giselle-engine.ts
  packages/giselle-engine/src/core/generations/generate-image.ts
  packages/giselle-engine/src/core/generations/internal/use-generation-executor.ts
  packages/telemetry/package.json
  packages/telemetry/src/index.ts
  pnpm-lock.yaml
Labels: Review effort 4/5

#1121 Add e2e test workflow
  .github/workflows/e2e.yml
  apps/studio.giselles.ai/package.json
  docs/packages-license.md
  pnpm-lock.yaml
Labels: codex, Review effort 2/5

#1115 feat(rag2): add QueryService implementation for RAG queries
  apps/studio.giselles.ai/app/giselle-engine.ts
  apps/studio.giselles.ai/lib/vector-stores/github-blob-stores.ts
  apps/studio.giselles.ai/package.json
  docs/packages-license.md
  packages/giselle-engine/package.json
  packages/giselle-engine/src/core/operations/execute-query.ts
  packages/giselle-engine/src/core/types.ts
  packages/rag2/README.md
  packages/rag2/package.json
  packages/rag2/src/database/index.ts
  packages/rag2/src/database/pgvector-registry.ts
  packages/rag2/src/database/postgres/index.ts
  packages/rag2/src/database/postgres/pool-manager.ts
  packages/rag2/src/database/types.ts
  packages/rag2/src/embedder/index.ts
  packages/rag2/src/embedder/openai.ts
  packages/rag2/src/embedder/types.ts
  packages/rag2/src/errors.test.ts
  packages/rag2/src/errors.ts
  packages/rag2/src/factories/factories.ts
  packages/rag2/src/factories/index.ts
  packages/rag2/src/factories/types.ts
  packages/rag2/src/factories/utils.ts
  packages/rag2/src/index.ts
  packages/rag2/src/query-service/index.ts
  packages/rag2/src/query-service/postgres/index.ts
  packages/rag2/src/query-service/types.ts
  packages/rag2/tsconfig.json
  packages/rag2/tsup.config.ts
  packages/rag2/turbo.json
  packages/rag2/vitest.config.mts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 4/5

#1134 Update AGENTS.md for codex
  AGENTS.md
Labels: Review effort 1/5

#1133 Refactor GitHub tools UI components and improve secret selection workflow
  internal-packages/workflow-designer-ui/src/editor/lib/use-workspace-secrets.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tools-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/button.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/dropdown-menu.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/empty-state.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/popover.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/select.tsx
  packages/giselle-engine/src/core/index.ts
  packages/giselle-engine/src/core/secrets/add-secret.ts
  packages/giselle-engine/src/core/secrets/get-workspace-secrets.ts
  packages/giselle-engine/src/core/secrets/index.ts
  packages/giselle-engine/src/http/router.ts
Labels: Review effort 3/5

#1135 Fix telemetry to skip query nodes
  packages/telemetry/src/index.ts
Labels: codex, Review effort 2/5

#1132 Remove unused files
  apps/studio.giselle.ai/app/(main)/settings/team/page.tsx
  apps/studio.giselle.ai/app/(main)/settings/team/team-name-form.tsx
Labels: Review effort 1/5

#1138 Add secrets management UI to Workflow Designer
  apps/playground/app/globals.css
  apps/studio.giselles.ai/app/globals.css
  internal-packages/ui/components/button.tsx
  internal-packages/ui/components/dialog.tsx
  internal-packages/ui/components/empty-state.tsx
  internal-packages/ui/components/table.tsx
  internal-packages/ui/package.json
  internal-packages/ui/style.css
  internal-packages/ui/tsconfig.json
  internal-packages/workflow-designer-ui/package.json
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/lib/use-workspace-secrets.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tools-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/secret/secret-table.tsx
  internal-packages/workflow-designer-ui/src/editor/side-menu/side-menu.tsx
  pnpm-lock.yaml
Labels: Review effort 4/5

#1140 Refactor: E2E test for login session reuse
  apps/studio.giselles.ai/.gitignore
  apps/studio.giselles.ai/playwright.config.ts
  apps/studio.giselles.ai/tests/e2e/.auth/.gitkeep
  apps/studio.giselles.ai/tests/e2e/global-setup.ts
  apps/studio.giselles.ai/tests/e2e/login.spec.ts
Labels: Review effort 2/5

#1145 Fix refactor app directory
  apps/studio.giselles.ai/app/(main)/apps/components.tsx
  apps/studio.giselles.ai/migrations/0034_curly_white_queen.sql
  apps/studio.giselles.ai/migrations/meta/0034_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
Labels: Review effort 2/5

#1127 feat: Add node reference utilities with improved type safety
  packages/text-editor-utils/src/extensions/source-extension.ts
  packages/text-editor-utils/src/index.ts
  packages/text-editor-utils/src/node-references/cleanup.ts
  packages/text-editor-utils/src/node-references/formatting.ts
  packages/text-editor-utils/src/node-references/index.ts
  packages/text-editor-utils/src/node-references/source-detection.ts
Labels: Review effort 3/5

#1144 chore(studio): migrate tailwindcss packages to catalog versioning
  apps/studio.giselles.ai/package.json
  docs/packages-license.md
  pnpm-lock.yaml
Labels: Review effort 2/5

#1143 Vector store v2
  apps/studio.giselles.ai/app/giselle-engine.ts
  apps/studio.giselles.ai/package.json
  internal-packages/ui/components/button.tsx
  internal-packages/ui/components/note.tsx
  internal-packages/ui/components/popover.tsx
  internal-packages/ui/components/select.tsx
  internal-packages/ui/package.json
  internal-packages/workflow-designer-ui/src/app/globals.css
  internal-packages/workflow-designer-ui/src/editor/data-source/data-source-table.tsx
  internal-packages/workflow-designer-ui/src/editor/data-source/index.ts
  internal-packages/workflow-designer-ui/src/editor/data-source/provider/github/index.tsx
  internal-packages/workflow-designer-ui/src/editor/data-source/provider/github/install-application.tsx
  internal-packages/workflow-designer-ui/src/editor/data-source/provider/github/unauthorized.tsx
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/lib/use-popup-window.tsx
  internal-packages/workflow-designer-ui/src/editor/lib/use-workspace-data-sources.ts
  internal-packages/workflow-designer-ui/src/editor/side-menu/side-menu.tsx
  packages/giselle-engine/src/core/data-source/create-data-source.ts
  packages/giselle-engine/src/core/data-source/get-workspace-data-sources.ts
  packages/giselle-engine/src/core/data-source/index.ts
  packages/giselle-engine/src/core/data-source/paths.ts
  packages/giselle-engine/src/core/data-source/types/object.ts
  packages/giselle-engine/src/core/index.ts
  packages/giselle-engine/src/core/types.ts
  packages/giselle-engine/src/core/vector-store/add-file-to-vector-store.ts
  packages/giselle-engine/src/core/vector-store/create-vector-store.ts
  packages/giselle-engine/src/core/vector-store/index.ts
  packages/giselle-engine/src/core/vector-store/paths.ts
  packages/giselle-engine/src/core/vector-store/types/interface.ts
  packages/giselle-engine/src/core/vector-store/types/object.ts
  packages/giselle-engine/src/http/router.ts
  packages/vector-store-adapters/package.json
  packages/vector-store-adapters/src/index.ts
  packages/vector-store-adapters/src/openai/index.ts
  packages/vector-store-adapters/tsconfig.json
  packages/vector-store-adapters/tsup.config.ts
  packages/vector-store-adapters/turbo.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 4/5

#1137 Use pg escapeIdentifier for SQL column names
  packages/rag2/src/query-service/postgres/index.ts
Labels: codex, Review effort 3/5

#1150 Add aria-label to all header menu items for E2E accessibility
  apps/studio.giselles.ai/app/(main)/nav.tsx
  apps/studio.giselles.ai/tests/e2e/header-menu.spec.ts
Labels: Review effort 2/5

#1152 Fix invalid URL handling in WebPage node
  internal-packages/workflow-designer-ui/src/editor/properties-panel/web-page-node-properties-panel/index.tsx
Labels: codex, Review effort 2/5

#1153 Add run history table and DM Mono font integration
  apps/playground/app/globals.css
  apps/playground/app/layout.tsx
  apps/studio.giselles.ai/app/globals.css
  apps/studio.giselles.ai/app/layout.tsx
  internal-packages/ui/components/table.tsx
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/run-history/run-history-table.tsx
Labels: Review effort 2/5

#1156 Fix copyAgent to duplicate agent names
  apps/studio.giselles.ai/app/(main)/apps/actions.ts
  packages/giselle-engine/src/core/index.ts
  packages/giselle-engine/src/core/workspaces/copy-workspace.ts
Labels: codex, Review effort 2/5

#1139 Proofreading: Manual Trigger Node
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/manual-trigger/manual-trigger-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/header/ui/trigger-input-dialog/dialog.tsx
Labels: Review effort 1/5

#1159 Proofreading: GitHub Action Node
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/index.tsx
  packages/flow/src/action/github.ts
Labels: Review effort 1/5

#1161 Fix manual trigger workflow referencing
  packages/workflow-utils/src/build-workflow-from-node.ts
Labels: codex, Review effort 2/5

#1167 Improve GoogleLanguageModelId Fallback Logic and Add Comprehensive Tests
  packages/language-model/src/costs/model-prices.ts
  packages/language-model/src/google.test.ts
  packages/language-model/src/google.ts
  packages/workflow-utils/src/test/test-data.ts
Labels: Review effort 3/5

#1169 Add mapping for legacy OpenAI model names to current model IDs
  packages/language-model/src/costs/model-prices.ts
  packages/language-model/src/openai.test.ts
  packages/language-model/src/openai.ts
  packages/workflow-utils/src/build-workflow-map.test.ts
  packages/workflow-utils/src/helper.test.ts
Labels: Review effort 3/5

#1173 Fix search domain filter validation
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/model/simple-domain-filter.tsx
Labels: codex, Review effort 2/5

#1163 fix: Implement node reference cleanup on connection deletion
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/input-panel.tsx
  packages/text-editor/src/react/source-extension-react.tsx
  packages/workflow-designer/package.json
  packages/workflow-designer/src/workflow-designer.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#1178 Fix Domain Limit Filter Size in the Perplexity Model Settings
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/model/search-domain-filter-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/model/simple-domain-filter.tsx
Labels: Review effort 2/5

#1179 Refactor runFlow execution
  packages/giselle-engine/src/core/flows/run-flow.ts
Labels: codex, Review effort 3/5

#1183 Update Anthropic Models and Improve Fallback Logic
  packages/language-model/src/anthropic.test.ts
  packages/language-model/src/anthropic.ts
  packages/language-model/src/costs/model-prices.ts
Labels: Review effort 3/5

#1187 chore: remove legacy rag package
  apps/studio.giselles.ai/app/giselle-engine.ts
  apps/studio.giselles.ai/app/services/vector-store/index.ts
  apps/studio.giselles.ai/app/services/vector-store/query-github-vector-store.ts
  apps/studio.giselles.ai/package.json
  packages/giselle-engine/package.json
  packages/giselle-engine/src/core/operations/execute-query.ts
  packages/giselle-engine/src/core/types.ts
  packages/github-tool/package.json
  packages/rag/package.json
  packages/rag/src/chunk.test.ts
  packages/rag/src/chunk.ts
  packages/rag/src/embed.ts
  packages/rag/src/index.ts
  packages/rag/src/ingest.ts
  packages/rag/src/query.test.ts
  packages/rag/src/query.ts
  packages/rag/src/types.ts
  packages/rag/tsconfig.json
  packages/rag/tsup.config.ts
  packages/rag/turbo.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1191 fix: Cannot delete app after removing all nodes (Blob not found error)
  apps/studio.giselles.ai/app/(main)/apps/actions.ts
  apps/studio.giselles.ai/app/(main)/apps/layout.tsx
  apps/studio.giselles.ai/app/dev/copy-agent/action.ts
  apps/studio.giselles.ai/app/dev/copy-agent/agent-id-form.tsx
  apps/studio.giselles.ai/app/dev/copy-agent/page.tsx
  apps/studio.giselles.ai/app/dev/get-blob/route.ts
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/lib/opentelemetry/types.ts
  apps/studio.giselles.ai/lib/opentelemetry/wrapper.ts
  apps/studio.giselles.ai/packages/actions.ts
  apps/studio.giselles.ai/packages/constants.ts
  apps/studio.giselles.ai/packages/lib/utils.ts
  apps/studio.giselles.ai/services/accounts/actions/initialize-account.ts
Labels: Review effort 4/5

#1192 Refactor: Store secrets in a password field & disable autocomplete
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tools-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/secret/secret-table.tsx
Labels: Review effort 2/5

#1136 Feature/refactor app directory
  apps/studio.giselles.ai/app/(main)/apps/actions.ts
  apps/studio.giselles.ai/app/(main)/apps/components.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/agent-card.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/agent-grid.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/create-agent-button.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/delete-agent-button.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/duplicate-agent-button.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/utils.ts
  apps/studio.giselles.ai/app/(main)/apps/layout.tsx
  apps/studio.giselles.ai/app/(main)/apps/myapps/page.tsx
  apps/studio.giselles.ai/app/(main)/apps/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/components/button.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/agent-usage-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/components/glass-dialog-content.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/delete-team.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/invitation-list-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/invite-member-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-name-form.tsx
  apps/studio.giselles.ai/packages/components/toasts.tsx
  biome.json
Labels: Review effort 4/5

#1194 Disable turbopack
  apps/studio.giselles.ai/lib/opentelemetry/types.ts
  apps/studio.giselles.ai/lib/opentelemetry/wrapper.ts
  apps/studio.giselles.ai/next.config.ts
  apps/studio.giselles.ai/package.json
  apps/studio.giselles.ai/services/external/google/user-client.ts
  docs/packages-license.md
  packages/web-search/src/self-made.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#1198 Add happy-dom dependency to playground and studio apps
  apps/playground/next.config.ts
  apps/playground/package.json
  apps/studio.giselles.ai/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1202 Implement Layout V2 feature flag and placeholder components
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/index.ts
  internal-packages/workflow-designer-ui/src/editor/v2/v2-placeholder.tsx
  packages/workspace/src/react/feature-flag.ts
  packages/workspace/src/react/workspace.tsx
Labels: Review effort 2/5

#1206 Fix agent deletion error
  apps/studio.giselles.ai/app/(main)/apps/actions.ts
Labels: codex, Review effort 2/5

#1205 refactor(apps): optimize light tracking performance and improve code structure
  apps/studio.giselles.ai/app/(main)/apps/components/agent-card.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/agent-grid.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/constants.ts
  apps/studio.giselles.ai/app/(main)/apps/components/light-overlay.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/types.ts
  apps/studio.giselles.ai/app/(main)/apps/components/use-light-tracking.ts
Labels: Review effort 3/5

#1208 (e2e test) Create and delete an app
  apps/studio.giselles.ai/app/(main)/apps/components/agent-card.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/delete-agent-button.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/duplicate-agent-button.tsx
  apps/studio.giselles.ai/app/(main)/apps/layout.tsx
  apps/studio.giselles.ai/app/(main)/layout.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/components/glass-dialog-content.tsx
  apps/studio.giselles.ai/tests/e2e/app-management.spec.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/editable-text.tsx
  internal-packages/workflow-designer-ui/src/header/component.tsx
Labels: Review effort 2/5

#1209 (e2e test) Allow PLAYWRIGHT_BASE_URL to be set via workflow_dispatch input
  .github/workflows/e2e.yml
Labels: Review effort 2/5

#1213 Refactor: Move telemetry module into Giselle Engine
  apps/playground/giselle-engine.ts
  apps/playground/package.json
  apps/studio.giselles.ai/app/giselle-engine.ts
  apps/studio.giselles.ai/package.json
  packages/giselle-engine/package.json
  packages/giselle-engine/src/core/generations/generate-text.ts
  packages/giselle-engine/src/core/generations/internal/use-generation-executor.ts
  packages/giselle-engine/src/core/index.ts
  packages/giselle-engine/src/core/telemetry/index.ts
  packages/giselle-engine/src/core/telemetry/types.ts
  packages/giselle-engine/src/core/types.ts
  packages/giselle-engine/src/react/generations/generation-runner.tsx
  packages/giselle-engine/src/react/index.ts
  packages/giselle-engine/src/react/telemetry/context.tsx
  packages/giselle-engine/src/react/telemetry/index.ts
  packages/telemetry/package.json
  packages/telemetry/tsconfig.json
  packages/telemetry/tsup.config.ts
  packages/telemetry/turbo.json
  packages/workspace/package.json
  packages/workspace/src/react/workspace.tsx
  pnpm-lock.yaml
Labels: Review effort 3/5

#1218 UI component showcase and button variants
  apps/playground/app/ui/button/page.tsx
  apps/playground/app/ui/page.tsx
  internal-packages/ui/components/button.tsx
Labels: Review effort 2/5

#1217 Refactor: Centralize Turborepo Build Configuration
  apps/studio.giselles.ai/turbo.json
  packages/github-tool/turbo.json
  turbo.json
Labels: Review effort 2/5, Possible security concern

#1219 Fix: Synchronize pnpm.lock with package.json
  pnpm-lock.yaml
Labels: Review effort 1/5

#1220 Feature/improve property panel
  .gitignore
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/github-action-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/file-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tab-content.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/index.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/resizable-section.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/floating-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/index.ts
  internal-packages/workflow-designer-ui/src/editor/v2/components/overlay-drawer.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-container.tsx
Labels: Review effort 4/5

#1225 Fix GitHub vector store availability check to prevent runtime errors
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  packages/giselle-engine/src/react/vector-store/context.tsx
Labels: Review effort 2/5

#1229 Refactor Button Component with Glassmorphic Styling
  internal-packages/ui/components/button.tsx
  internal-packages/ui/style.css
  internal-packages/ui/styles/glassmorphic-button.css
Labels: Review effort 2/5

#1230 Add UI component playground with Button and Dialog components
  apps/playground/app/ui/button/page.tsx
  apps/playground/app/ui/dialog/page.tsx
  apps/playground/app/ui/layout.tsx
  apps/playground/app/ui/nav-link.tsx
  apps/playground/app/ui/page.tsx
  apps/playground/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1232 Refactor: Update tools panel to use shared UI components
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tools-panel.tsx
Labels: Review effort 2/5

#1226 refactor: Prepare RAG package for differential ingest implementation
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/ingest-github-repository.ts
  packages/github-tool/src/blob-loader.ts
  packages/rag/src/document-loader/index.ts
  packages/rag/src/document-loader/types.ts
  packages/rag/src/ingest/embedder.ts
  packages/rag/src/ingest/index.ts
  packages/rag/src/ingest/ingest-pipeline.ts
  packages/rag/src/ingest/pipeline.test.ts
  packages/rag/src/ingest/pipeline.ts
  packages/rag/src/ingest/retry.ts
Labels: Review effort 4/5

#1235 Update UI components and standardize styles
  apps/playground/app/ui/dialog/page.tsx
  apps/playground/app/ui/layout.tsx
  apps/playground/app/ui/select/page.tsx
  internal-packages/ui/components/button.tsx
  internal-packages/ui/components/dialog.tsx
  internal-packages/ui/components/popover.tsx
  internal-packages/ui/components/select.tsx
  internal-packages/ui/style.css
  internal-packages/workflow-designer-ui/src/editor/data-source/data-source-table.tsx
Labels: Review effort 2/5

#1237 Fix supabase runtime warning
  apps/playground/next.config.ts
  apps/studio.giselles.ai/next.config.ts
Labels: codex, Review effort 2/5

#1234 Fix openai web page handling
  packages/giselle-engine/src/core/generations/utils.ts
Labels: codex, Review effort 3/5

#1241 feat: add orphaned repository warning for GitHub vector store nodes
  internal-packages/workflow-designer-ui/src/editor/lib/use-github-vector-store-status.ts
  internal-packages/workflow-designer-ui/src/editor/node/ui/github-node-info.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
Labels: Review effort 3/5

#1239 Implement Run Button for Workflow Execution
  internal-packages/ui/components/button.tsx
  internal-packages/ui/components/dialog.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/overlay-drawer.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-header.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/v2-placeholder.tsx
Labels: Review effort 3/5

#1246 fix: use REQUIRED_COLUMN_KEYS constant instead of hardcoded column names
  packages/rag/src/query-service/postgres/index.ts
Labels: Review effort 2/5

#1240 Add Node-based vault driver
  apps/playground/giselle-engine.ts
  apps/playground/lib/vault-driver.ts
  apps/playground/turbo.json
  packages/giselle-engine/src/core/secrets/add-secret.ts
  packages/giselle-engine/src/core/secrets/decrypt-secret.ts
  packages/giselle-engine/src/core/types.ts
  packages/giselle-engine/src/next/next-giselle-engine.test.ts
Labels: codex, Review effort 4/5, Possible security concern

#1250 Use Radix Dialog for floating panel
  internal-packages/workflow-designer-ui/src/editor/v2/components/floating-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-container.tsx
Labels: codex, Review effort 3/5

#1242 perf: parallelize ingest processing for improved performance
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/route.ts
  packages/rag/src/ingest/pipeline.ts
  packages/rag/src/ingest/utils.ts
Labels: Review effort 4/5

#1248 Unify resize handle styling across V2 layout
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/generation-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tab-content.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/index.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/panel-spacing.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/resizable-section.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/floating-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-container.tsx
Labels: Review effort 3/5

#1251 Enable GitHub Vector Store flag by default
  apps/studio.giselles.ai/flags.ts
Labels: Review effort 2/5

#1261 Implement GitHub tool integration and UI enhancements
  apps/playground/app/ui/layout.tsx
  apps/playground/app/ui/select/page.tsx
  apps/playground/app/ui/toggle/page.tsx
  internal-packages/ui/components/button.tsx
  internal-packages/ui/components/dialog.tsx
  internal-packages/ui/components/popover.tsx
  internal-packages/ui/components/toggle.tsx
  internal-packages/ui/package.json
  internal-packages/ui/style.css
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tools-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/button.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/dialog.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/dropdown-menu.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/popover.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/select.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/tool-configuration-dialog.tsx
Labels: Review effort 4/5, Possible security concern

#1254 Improve text node editor
  docs/packages-license.md
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/prompt-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tab-content.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/resizable-section.tsx
  packages/text-editor/package.json
  packages/text-editor/src/react/component.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 2/5

#1262 Add placeholder text to text editors
  internal-packages/workflow-designer-ui/src/app/globals.css
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/prompt-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-node-properties-panel/index.tsx
  packages/text-editor/src/react/component.tsx
Labels: Review effort 2/5

#1264 Fix playground footer
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-footer.tsx
  internal-packages/workflow-designer-ui/src/ui/tooltip.tsx
Labels: Review effort 2/5

#1266 feat: add layout v2 flag conditional rendering in workspace page
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/page.tsx
Labels: Review effort 2/5

#1271 Disable LayoutV3 feature flag and clean up references
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/file-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tab-content.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/file-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-header.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/v2-placeholder.tsx
Labels: Review effort 2/5

#1273 Add Webpack Bundle Analyzer to Next.js configuration
  apps/studio.giselles.ai/next.config.ts
  apps/studio.giselles.ai/package.json
  docs/packages-license.md
  pnpm-lock.yaml
Labels: Review effort 2/5

#1188 Allow members to leave a team
  apps/studio.giselles.ai/app/(main)/settings/account/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/actions.ts
Labels: codex, Review effort 3/5
