Repository giselles-ai/giselle, pull requests merged in 2025-07, with the labels that each got.

#1280 Add new black-200 color and auth component styles in CSS
  apps/playground/app/globals.css
  apps/studio.giselles.ai/app/globals.css
Labels: Review effort 2/5

#1279 Fix: Prevent empty query execution in vector store
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/index.tsx
  packages/giselle-engine/src/core/operations/execute-query.ts
Labels: Review effort 2/5

#1282 Support flow name updates in layoutV2 editor components
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/page.tsx
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-header.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/v2-placeholder.tsx
Labels: Review effort 2/5

#1276 Refactor workflow-designer to React-only
  apps/playground/package.json
  internal-packages/workflow-designer-ui/package.json
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/ui/github-action-configured-view.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/input-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/tabs.tsx
  internal-packages/workflow-designer-ui/src/editor/run-button/run-button.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/state.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
  internal-packages/workflow-designer-ui/src/header/component.tsx
  internal-packages/workflow-designer-ui/src/header/run-button/run-button.tsx
  internal-packages/workflow-designer-ui/src/ui/header.tsx
  packages/giselle-engine/src/index.ts
  packages/giselle-engine/src/react/flow/context.tsx
  packages/giselle-engine/src/react/flow/hooks/index.ts
  packages/giselle-engine/src/react/flow/hooks/use-add-node.ts
  packages/giselle-engine/src/react/flow/hooks/use-connection.ts
  packages/giselle-engine/src/react/flow/hooks/use-copy-node.ts
  packages/giselle-engine/src/react/flow/hooks/use-node-update.ts
  packages/giselle-engine/src/react/flow/hooks/use-properties-panel.ts
  packages/giselle-engine/src/react/flow/hooks/use-workflow-designer.ts
  packages/giselle-engine/src/react/flow/index.ts
  packages/giselle-engine/src/react/flow/is-supported-connection.test.ts
  packages/giselle-engine/src/react/flow/types.ts
  packages/giselle-engine/src/react/flow/utils/index.ts
  packages/giselle-engine/src/react/flow/utils/is-supported-connection.ts
  packages/giselle-engine/src/react/index.ts
  packages/giselle-engine/src/utils/index.ts
  packages/giselle-engine/src/utils/node-default-name.ts
  packages/giselle-engine/src/utils/node-factories.ts
  packages/giselle-sdk/package.json
  packages/giselle-sdk/src/react/index.ts
  packages/node-utils/package.json
  packages/node-utils/src/index.ts
  packages/node-utils/tsconfig.json
  packages/node-utils/tsup.config.ts
  packages/node-utils/turbo.json
  packages/text-editor-utils/src/index.ts
  packages/text-editor/package.json
  packages/text-editor/src/react/source-extension-react.tsx
  packages/workflow-designer/package.json
  packages/workflow-designer/src/index.ts
  packages/workflow-designer/src/react/index.ts
  packages/workflow-designer/src/react/state/index.ts
  packages/workflow-designer/src/react/state/use-view.ts
  packages/workflow-designer/src/react/workflow-designer-context.tsx
  packages/workflow-designer/src/workflow-designer.ts
  packages/workflow-designer/tsconfig.json
  packages/workflow-designer/tsup.config.ts
  packages/workflow-designer/turbo.json
  packages/workspace/package.json
  packages/workspace/src/react/hooks.ts
  packages/workspace/src/react/index.ts
  packages/workspace/src/react/workspace.tsx
  pnpm-lock.yaml
Labels: codex, Review effort 4/5

#1284 Refactor WorkflowDesignerProvider to use workspace reducer pattern
  packages/giselle-engine/src/react/flow/context.tsx
  packages/giselle-engine/src/react/flow/hooks/index.ts
  packages/giselle-engine/src/react/flow/hooks/use-add-node.ts
  packages/giselle-engine/src/react/flow/hooks/use-connection.ts
  packages/giselle-engine/src/react/flow/hooks/use-copy-node.ts
  packages/giselle-engine/src/react/flow/hooks/use-node-update.ts
  packages/giselle-engine/src/react/flow/hooks/use-workspace-reducer.ts
Labels: Review effort 4/5

#1292 feat(studio): Extract migration for errorCode and retryAfter columns
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/migrations/0035_big_the_hunter.sql
  apps/studio.giselles.ai/migrations/meta/0035_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
Labels: Review effort 2/5

#1289 Fix run button trigger logic conditional
  internal-packages/ui/components/dropdown-menu.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
Labels: Review effort 2/5

#1277 Allow members to leave team
  apps/studio.giselles.ai/app/(main)/settings/team/members/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-members-list-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-members-list.tsx
Labels: codex, Review effort 2/5

#1291 feat: add BlobDownloadLoader for efficient initial repository ingestion
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/ingest-github-repository.ts
  docs/packages-license.md
  packages/github-tool/package.json
  packages/github-tool/src/blob-download-loader.ts
  packages/github-tool/src/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 4/5, Possible security concern

#1295 Feature/vector store settings
  apps/studio.giselles.ai/app/(main)/apps/layout.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/invite-member-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/data.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/error-messages.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-list.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-registration-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/status-cards.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/types.ts
  apps/studio.giselles.ai/app/globals.css
  apps/studio.giselles.ai/components/ui/glass-button.tsx
  apps/studio.giselles.ai/tailwind.config.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-node-properties-panel/index.tsx
Labels: Review effort 4/5

#1300 test(e2) Added the "Vector Stores" test case to the header menu
  apps/studio.giselles.ai/tests/e2e/header-menu.spec.ts
Labels: Review effort 1/5

#1298 refactor: optimize node generation status tracking with useRef
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
Labels: Review effort 2/5

#1302 feat: Add conditional Input tab rendering based on layoutV2 feature flag
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tab-content.tsx
Labels: Review effort 2/5

#1301 Enhance DropdownMenu component with group support and v2 layout option
  internal-packages/ui/components/dropdown-menu.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/ui/github-action-configured-view.tsx
Labels: Review effort 4/5

#1304 Hide Input tab in Query Node when layoutV2 feature flag is enabled
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/index.tsx
Labels: Review effort 2/5

#1314 Add table component demo page
  apps/playground/app/ui/layout.tsx
  apps/playground/app/ui/table/page.tsx
Labels: codex, Review effort 2/5

#1311 Replace run history table with Table component
  internal-packages/workflow-designer-ui/src/editor/run-history/run-history-table.tsx
Labels: codex

#1312 Use shared Input component in tool providers
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/postgres.tsx
Labels: codex, Review effort 2/5

#1309 Update Table component styling
  apps/playground/app/ui/layout.tsx
  apps/playground/app/ui/table/page.tsx
  internal-packages/ui/components/table.tsx
  internal-packages/workflow-designer-ui/src/editor/run-history/run-history-table.tsx
Labels: codex, Review effort 2/5

#1317 Add UI page link in playground home
  apps/playground/app/page.tsx
Labels: codex, Review effort 1/5

#1322 Refactor tool provider dialogs
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/postgres.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/use-tool-provider-connection.tsx
Labels: codex, Review effort 3/5

#1324 Rename ToolProviderSecretType to ToolProviderSecretTypeValue
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/postgres.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/use-tool-provider-connection.tsx
Labels: Review effort 2/5

#1263 Fix workspace cache issue causing data persistence problems
  apps/playground/supabase-storage-driver.ts
  apps/studio.giselles.ai/supabase-storage-driver.ts
  packages/giselle-engine/src/core/workspaces/utils.ts
Labels: Review effort 2/5

#1315 feat(studio): add re-link functionality for invalid GitHub installations
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/diagnostic-modal.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/types.ts
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/ingest-github-repository.ts
Labels: Review effort 4/5

#1332 Remove search methods from GitHub tool catalog
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github.tsx
Labels: Review effort 2/5

#1331 Update GitHub tools flag to use edge config
  apps/studio.giselles.ai/flags.ts
Labels: Review effort 3/5

#1334 Remove auto-close behavior from workflow designer panels
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-container.tsx
Labels: Review effort 2/5

#1336 Remove unused table styles
  internal-packages/workflow-designer-ui/src/editor/shared/table-styles.ts
Labels: codex, Review effort 1/5

#1337 Redesign left panel with resizable functionality
  internal-packages/ui/style.css
  internal-packages/workflow-designer-ui/src/editor/v2/components/left-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/resizable-panel/panel-wrapper.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-container.tsx
Labels: Review effort 3/5

#1339 Update panel padding and resize handle styling
  internal-packages/workflow-designer-ui/src/editor/run-history/run-history-table.tsx
  internal-packages/workflow-designer-ui/src/editor/secret/secret-table.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/left-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-container.tsx
Labels: Review effort 2/5

#1341 Replace div elements with semantic HTML and buttons for accessibility
  apps/studio.giselles.ai/app/(main)/apps/components/agent-card.tsx
  apps/studio.giselles.ai/app/dev/tabui/components/custom-node.tsx
  apps/studio.giselles.ai/app/dev/tabui/components/node-selector.tsx
  apps/studio.giselles.ai/app/dev/tabui/components/spinner.tsx
  apps/studio.giselles.ai/app/dev/tabui/components/tab.tsx
  apps/studio.giselles.ai/app/dev/tabui/contexts/drag-and-drop.tsx
  apps/studio.giselles.ai/app/dev/tabui/page.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/file-node-properties-panel/file-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/resizable-section.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/file-node-properties-panel/file-panel.tsx
Labels: Review effort 2/5

#1344 Prefix unused variables with underscore
  apps/playground/app/ui/dropdown-menu/page.tsx
  apps/playground/middleware.ts
  apps/playground/supabase-storage-driver.ts
Labels: Review effort 1/5

#1343 Fix middleware return type and implementation
  apps/studio.giselles.ai/lib/supabase/middleware.ts
  apps/studio.giselles.ai/middleware.ts
Labels: Review effort 2/5

#1345 Fix Biome warnings in data-mod package
  packages/data-mod/src/mods/rename-action-to-operation.test.ts
  packages/data-mod/src/mods/rename-action-to-operation.ts
Labels: codex, Review effort 1/5

#1347 Fix Biome warnings in data-type package
  packages/data-type/src/node/variables/text.ts
  packages/data-type/src/node/variables/vector-store.ts
Labels: codex, Review effort 1/5

#1350 Fix Biome warnings in language-model package
  packages/language-model/src/base.ts
  packages/language-model/src/costs/calculator.ts
  packages/language-model/src/costs/index.test.ts
  packages/language-model/src/costs/model-prices.test.ts
  packages/language-model/src/fal.test.ts
  packages/language-model/src/fal.ts
Labels: codex, Review effort 2/5

#1358 Fix edge deletion logic in v2 container
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-container.tsx
Labels: codex, Review effort 3/5

#1346 Fix Biome warnings in studio app
  apps/studio.giselles.ai/app/(auth)/auth/connect/[provider]/route.ts
  apps/studio.giselles.ai/app/(auth)/join/[token]/page.tsx
  apps/studio.giselles.ai/app/(auth)/join/[token]/signup/actions.ts
  apps/studio.giselles.ai/app/(auth)/lib/get-team-membership-by-agent-id.ts
  apps/studio.giselles.ai/app/(auth)/login/login.ts
  apps/studio.giselles.ai/app/(auth)/password_reset/actions.ts
  apps/studio.giselles.ai/app/(auth)/signup/verify-email/verify-email.ts
  apps/studio.giselles.ai/app/(main)/apps/components/agent-card.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/light-overlay.tsx
  apps/studio.giselles.ai/app/(main)/apps/myapps/page.tsx
  apps/studio.giselles.ai/app/(main)/apps/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/account-display-name-form.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/google-authentication.tsx
  apps/studio.giselles.ai/app/(main)/settings/components/menu-link.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/invitation-list-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/invite-member-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/members/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-members-form.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-members-list-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-name-form.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-registration-dialog.tsx
  apps/studio.giselles.ai/app/.well-known/vercel/flags/route.ts
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/ingest-github-repository.ts
  apps/studio.giselles.ai/app/dev/connect-spreadsheet/_utils/auth.ts
  apps/studio.giselles.ai/app/dev/connect-spreadsheet/page.tsx
  apps/studio.giselles.ai/app/dev/connect-spreadsheet/types/next-auth.d.ts
  apps/studio.giselles.ai/components/giselle-logo.tsx
  apps/studio.giselles.ai/components/theme-provider.tsx
  apps/studio.giselles.ai/components/ui/accordion.tsx
  apps/studio.giselles.ai/components/ui/dialog.tsx
  apps/studio.giselles.ai/drizzle.config.ts
  apps/studio.giselles.ai/lib/opentelemetry/wrapper.ts
  apps/studio.giselles.ai/lib/signed-cookie.test.ts
  apps/studio.giselles.ai/lib/supabase/middleware.ts
  apps/studio.giselles.ai/packages/components/toast.tsx
  apps/studio.giselles.ai/services/external/github/user-client.ts
  apps/studio.giselles.ai/services/teams/components/team-creation-form.tsx
  apps/studio.giselles.ai/services/teams/components/team-selection-form.tsx
  apps/studio.giselles.ai/supabase-storage-driver.ts
  apps/studio.giselles.ai/tests/e2e/app-management.spec.ts
  internal-packages/workflow-designer-ui/src/editor/v2/components/floating-properties-panel.tsx
Labels: codex, Review effort 2/5

#1362 feat: Improve error handling for query execution
  packages/giselle-engine/src/core/operations/execute-query.ts
  packages/rag/src/errors.ts
Labels: Review effort 3/5

#1364 Fix node deletion cleanup
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-container.tsx
Labels: codex, Review effort 3/5

#1365 Fix unused imports and variables in workflow-designer-ui
  internal-packages/workflow-designer-ui/src/editor/components/keyboard-shortcuts.tsx
  internal-packages/workflow-designer-ui/src/editor/data-source/data-source-table.tsx
  internal-packages/workflow-designer-ui/src/editor/debug.tsx
  internal-packages/workflow-designer-ui/src/editor/keyboard-shortcuts.tsx
  internal-packages/workflow-designer-ui/src/editor/lib/use-github-vector-store-status.ts
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/github-action-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/ui/github-action-configured-view.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/file-node-properties-panel/file-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/file-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/generation-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/model/anthropic.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/model/search-domain-filter-panel-enhanced.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/prompt-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/postgres-tools.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/postgres.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/ui/configured-views/manual-trigger-configured-view.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/panel-spacing.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/web-page-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/floating-node/component.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-header.tsx
  internal-packages/workflow-designer-ui/src/header/component.tsx
  internal-packages/workflow-designer-ui/src/header/ui/trigger-input-dialog/helpers.ts
  internal-packages/workflow-designer-ui/src/hooks/use-trigger.ts
  internal-packages/workflow-designer-ui/src/icons/circle-check.tsx
  internal-packages/workflow-designer-ui/src/icons/node/file-node.tsx
  internal-packages/workflow-designer-ui/src/icons/triangle-alert.tsx
  internal-packages/workflow-designer-ui/src/ui/clipboard-button.tsx
  internal-packages/workflow-designer-ui/src/ui/domain-tag-input.tsx
  internal-packages/workflow-designer-ui/src/ui/generation-view.tsx
  internal-packages/workflow-designer-ui/src/ui/read-only-banner.tsx
  internal-packages/workflow-designer-ui/src/ui/search-domain-filter-enhanced.tsx
  internal-packages/workflow-designer-ui/src/ui/search-domain-filter.tsx
  internal-packages/workflow-designer-ui/src/ui/share-modal.tsx
  internal-packages/workflow-designer-ui/src/ui/tag-input.tsx
  internal-packages/workflow-designer-ui/src/ui/user-presence.tsx
Labels: Review effort 2/5

#1366 Remove unnecessary fragment wrappers in UI components
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tab-content.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
Labels: Review effort 2/5

#1369 Add refresh button to run history table
  internal-packages/workflow-designer-ui/src/editor/run-history/run-history-table.tsx
Labels: Review effort 2/5

#1370 Add loading state to run history refresh button
  internal-packages/workflow-designer-ui/src/editor/run-history/run-history-table.tsx
Labels: Review effort 2/5

#1381 Proofreading: Update Vector Store Nodes/Query Nodes related text
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-list.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/status-cards.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
  internal-packages/workflow-designer-ui/src/ui/query-result-view.tsx
Labels: Review effort 1/5

#1265 feat: redirect to workspace after login with proper error handling
  apps/studio.giselles.ai/app/(auth)/actions.ts
  apps/studio.giselles.ai/app/(auth)/components/oauth-providers.tsx
  apps/studio.giselles.ai/app/(auth)/lib/index.ts
  apps/studio.giselles.ai/app/(auth)/lib/validate-return-url.ts
  apps/studio.giselles.ai/app/(auth)/login/login-form.tsx
  apps/studio.giselles.ai/app/(auth)/login/login.ts
  apps/studio.giselles.ai/app/(auth)/login/page.tsx
  apps/studio.giselles.ai/app/(auth)/types.ts
  apps/studio.giselles.ai/app/not-found.tsx
  apps/studio.giselles.ai/middleware.ts
Labels: Review effort 3/5, Possible security concern

#1383 Rename Query Node output port
  packages/giselle-engine/src/utils/node-factories.ts
Labels: codex, Review effort 1/5

#1385 feat: add manual ingest trigger for GitHub vector stores
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-list.tsx
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/route.ts
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/types.ts
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/utils.ts
  apps/studio.giselles.ai/app/giselle-engine.ts
  apps/studio.giselles.ai/lib/vector-stores/github-blob-stores.ts
  apps/studio.giselles.ai/lib/vector-stores/github/database.ts
  apps/studio.giselles.ai/lib/vector-stores/github/index.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/build-octokit.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/chunk-store.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/fetch-ingest-targets.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/ingest-github-blobs.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/process-repository.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/telemetry.ts
  apps/studio.giselles.ai/lib/vector-stores/github/query/resolver.ts
  apps/studio.giselles.ai/lib/vector-stores/github/query/service.ts
  apps/studio.giselles.ai/lib/vector-stores/github/types.ts
Labels: Review effort 4/5

#1373 Add custom storage implementation for Giselle
  docs/adr/0004-giselle-storage.md
Labels: Review effort 2/5

#1374 Add experimental storage interface to core exports
  packages/giselle-engine/src/core/experimental_storage/index.ts
  packages/giselle-engine/src/core/experimental_storage/types/interface.ts
  packages/giselle-engine/src/core/index.ts
Labels: Review effort 2/5

#1376 Add Supabase storage driver implementation
  docs/packages-license.md
  packages/supabase-driver/package.json
  packages/supabase-driver/src/index.ts
  packages/supabase-driver/src/storage/supabase-storage-driver.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 3/5, Possible security concern

#1379 Add filesystem storage driver implementation
  packages/giselle-engine/src/core/experimental_storage/fs-storage-driver.ts
  packages/giselle-engine/src/core/experimental_storage/index.ts
Labels: Review effort 3/5, Possible security concern

#1390 Fix web page node: use updateNodeData instead of workflow's updateName
  internal-packages/workflow-designer-ui/src/editor/properties-panel/web-page-node-properties-panel/index.tsx
Labels: Review effort 2/5

#1355 Feature/query node UI minimal
  apps/studio.giselles.ai/app/(main)/apps/myapps/page.tsx
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/generation-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/input-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
  internal-packages/workflow-designer-ui/src/ui/query-result-view.tsx
  packages/text-editor/src/react/component.tsx
  tools/storage-migration/index.ts
Labels: Review effort 3/5

#1389 Add memory storage driver implementation
  packages/giselle-engine/src/core/experimental_storage/index.ts
  packages/giselle-engine/src/core/experimental_storage/memory-storage-driver.ts
Labels: Review effort 2/5

#1356 Feature/vector store UI improvements
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-registration-dialog.tsx
  internal-packages/ui/components/note.tsx
  internal-packages/ui/components/toggle.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
Labels: Review effort 3/5, Possible security concern

#1391 test: add E2E tests for login redirect functionality
  apps/studio.giselles.ai/tests/e2e/app-management.spec.ts
  apps/studio.giselles.ai/tests/e2e/global-setup.ts
  apps/studio.giselles.ai/tests/e2e/helpers/login.ts
  apps/studio.giselles.ai/tests/e2e/helpers/regex.ts
  apps/studio.giselles.ai/tests/e2e/login-redirect.spec.ts
Labels: Review effort 2/5

#1392 Fix node detection logic in run button component
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
Labels: Review effort 2/5

#1386 Add experimental storage feature flag
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  packages/giselle-engine/src/react/feature-flags/context.ts
  packages/giselle-engine/src/react/workspace/provider.tsx
Labels: Review effort 2/5

#1388 Add experimental Supabase storage driver support
  apps/playground/giselle-engine.ts
  apps/playground/package.json
  apps/studio.giselles.ai/app/giselle-engine.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/github-trigger-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/manual-trigger/manual-trigger-properties-panel.tsx
  packages/giselle-engine/src/core/flows/configure-trigger.ts
  packages/giselle-engine/src/core/flows/run-flow.ts
  packages/giselle-engine/src/core/github/event-handlers.ts
  packages/giselle-engine/src/core/index.ts
  packages/giselle-engine/src/core/types.ts
  packages/giselle-engine/src/core/workspaces/copy-workspace.ts
  packages/giselle-engine/src/core/workspaces/create-sample-workspace.ts
  packages/giselle-engine/src/core/workspaces/get-workspace.ts
  packages/giselle-engine/src/core/workspaces/utils.ts
  packages/giselle-engine/src/http/router.ts
  packages/giselle-engine/src/next/next-giselle-engine.test.ts
  packages/giselle-engine/src/react/generations/generation-runner.tsx
  packages/giselle-engine/src/react/workspace/provider.tsx
  pnpm-lock.yaml
Labels: Review effort 4/5, Possible security concern

#1398 Move misaligned get-github-vector-stores.ts to proper location
  apps/studio.giselles.ai/app/services/vector-store/index.ts
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/lib/vector-stores/github/get-github-vector-stores.ts
  apps/studio.giselles.ai/lib/vector-stores/github/index.ts
Labels: Review effort 2/5

#1368 Feature/enhance node duplicate functionality
  internal-packages/ui/components/note.tsx
  internal-packages/workflow-designer-ui/src/editor/context-menu/index.tsx
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/keyboard-shortcuts.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/v2-placeholder.tsx
  internal-packages/workflow-designer-ui/src/ui/select.tsx
Labels: Review effort 4/5

#1405 test: add e2e tests for protected paths authentication
  apps/studio.giselles.ai/playwright.config.ts
  apps/studio.giselles.ai/tests/e2e/non-authenticated/login-redirect.spec.ts
  apps/studio.giselles.ai/tests/e2e/non-authenticated/protected-paths-auth.spec.ts
Labels: Review effort 3/5

#1406 Set empty search path for Supabase vault functions
  packages/supabase-driver/src/vault/supabase-rpc.sql
Labels: Review effort 2/5

#1413 Add staged property with default false to ManualFlowTrigger
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/manual-trigger/manual-trigger-properties-panel.tsx
  packages/data-type/src/flow/trigger/manual.test.ts
  packages/data-type/src/flow/trigger/manual.ts
Labels: Review effort 2/5

#1422 Fix dynamic server usage error in vector stores page
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
Labels: Review effort 2/5

#1416 Add staged toggle to manual trigger properties panel
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/manual-trigger/manual-trigger-properties-panel.tsx
Labels: Review effort 2/5

#1429 Add flow_triggers table to database schema
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/migrations/0036_workable_hiroim.sql
  apps/studio.giselles.ai/migrations/meta/0036_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
  packages/giselle-engine/src/core/types.ts
Labels: Review effort 2/5

#1387 fix: remove page reload on account settings update
  apps/studio.giselles.ai/app/(main)/settings/account/account-display-name-form.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/actions.ts
Labels: Review effort 2/5

#1436 fix: use defaultName for consistent node display names across UI
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/prompt-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/prompt-panel.tsx
Labels: Review effort 2/5

#1438 fix: Fix dropdown menu z-index issue in ImageGenerationNode
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/prompt-panel.tsx
Labels: Review effort 2/5

#1437 fix: Add missing connection restrictions for ImageGenerationNode
  packages/giselle-engine/src/react/flow/utils/is-supported-connection.test.ts
  packages/giselle-engine/src/react/flow/utils/is-supported-connection.ts
Labels: Review effort 2/5

#1441 Add knip for unused code detection
  .github/workflows/ci.yml
  docs/packages-license.md
  knip.jsonc
  package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1442 Convert knip config from JSON to TypeScript
  knip.jsonc
  knip.ts
Labels: Review effort 2/5

#1432 Add unique index on flow_triggers.sdkFlowTriggerId and implement flow trigger callbacks
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/migrations/0037_safe_korvac.sql
  apps/studio.giselles.ai/migrations/meta/0037_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/manual-trigger/manual-trigger-properties-panel.tsx
  packages/giselle-engine/src/react/flow-trigger/index.ts
  packages/giselle-engine/src/react/index.ts
  packages/giselle-engine/src/react/workspace/provider.tsx
Labels: Review effort 3/5

#1443 Refactor Supabase URL handling in image configuration
  apps/studio.giselles.ai/next.config.ts
Labels: Review effort 2/5

#1433 Refactor schema constraints to use array syntax
  apps/studio.giselles.ai/drizzle/schema.ts
Labels: Review effort 2/5

#1449 feat(language-model): enable Web Search for OpenAI o3 & o4-mini models
  packages/language-model/src/openai.ts
Labels: Review effort 2/5

#1455 Enable classMembers rule in knip configuration
  knip.ts
Labels: Review effort 1/5

#1456 Remove duplicate rule from knip config and simplify Source type usage
  knip.ts
  packages/data-type/src/generation/output.ts
Labels: Review effort 2/5

#1460 Add GitHub trigger UI components with event selection workflow
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/components/event-selection-step.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/components/event-type-display.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/components/icons/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/components/install-application.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/components/repository-display.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/components/unauthorized.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/github-trigger-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/utils/trigger-configuration.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/ui/configured-views/github-trigger-configured-view.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/select-repository.tsx
Labels: Review effort 4/5

#1467 Add team-based flow selection component to stage page
  apps/studio.giselles.ai/app/stage/flow-select.tsx
  apps/studio.giselles.ai/app/stage/page.tsx
Labels: Review effort 3/5

#1468 Update command from `pnpm prune` to `pnpm tidy` in documentation
  CLAUDE.md
Labels: Review effort 1/5

#1439 feat(github-tool): Add GitHub Pull Request loader for RAG/vector search
  packages/github-tool/src/document-loaders/blobs/archive-loader.ts
  packages/github-tool/src/document-loaders/blobs/index.ts
  packages/github-tool/src/document-loaders/blobs/tree-loader.ts
  packages/github-tool/src/document-loaders/index.ts
  packages/github-tool/src/document-loaders/pull-requests/cache.ts
  packages/github-tool/src/document-loaders/pull-requests/fetchers.ts
  packages/github-tool/src/document-loaders/pull-requests/index.ts
  packages/github-tool/src/document-loaders/pull-requests/loader.ts
  packages/github-tool/src/document-loaders/pull-requests/queries.ts
  packages/github-tool/src/document-loaders/pull-requests/types.ts
  packages/github-tool/src/document-loaders/utils.ts
  packages/github-tool/src/graphql.ts
  packages/github-tool/src/index.ts
Labels: Review effort 4/5

#1470 Update workflow documentation and change vitest command to run mode
  CLAUDE.md
  packages/rag/package.json
Labels: Review effort 1/5

#1473 Replace legacy UI with V2 workflow designer
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/page.tsx
  internal-packages/workflow-designer-ui/src/editor/index.tsx
  internal-packages/workflow-designer-ui/src/editor/run-button/index.ts
  internal-packages/workflow-designer-ui/src/editor/run-button/run-button.tsx
  internal-packages/workflow-designer-ui/src/editor/run-button/ui/button.tsx
  internal-packages/workflow-designer-ui/src/editor/side-menu/index.ts
  internal-packages/workflow-designer-ui/src/editor/side-menu/side-menu.tsx
Labels: Review effort 4/5

#1472 UI improvements
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/github-action-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/generation-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/ui/common/repository-block.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/select-repository.tsx
Labels: Review effort 2/5

#1478 Remove feature flag and simplify text generation panel UI
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/resizable-section.tsx
Labels: Review effort 2/5

#1480 Remove feature flag and simplify properties panel UI code
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/panel-spacing.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/ui/properties-panel.tsx
Labels: Review effort 2/5

#1482 Remove layoutV2 feature flag and Input tab from image generation panel
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/index.tsx
Labels: Review effort 2/5

#1485 Remove layoutV2 flag and references
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  packages/giselle-engine/src/react/feature-flags/context.ts
  packages/giselle-engine/src/react/workspace/provider.tsx
Labels: Review effort 2/5

#1486 Remove legacy GitHub and Postgres tools panels
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tab-content.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/github-tools.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/postgres-tools.tsx
Labels: Review effort 2/5

#1488 Remove GitHub tools feature flag
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tab-content.tsx
  packages/giselle-engine/src/react/feature-flags/context.ts
  packages/giselle-engine/src/react/workspace/provider.tsx
Labels: Review effort 2/5

#1489 Replace FlowSelect with Form component for stage actions
  apps/studio.giselles.ai/app/stage/flow-select.tsx
  apps/studio.giselles.ai/app/stage/form.tsx
  apps/studio.giselles.ai/app/stage/helpers.ts
  apps/studio.giselles.ai/app/stage/page.tsx
Labels: Review effort 3/5

#1491 refactor(rag): separate column mapping concerns between chunk-store and query-service
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/chunk-store.ts
  apps/studio.giselles.ai/lib/vector-stores/github/query/service.ts
  packages/rag/src/chunk-store/column-mapping.ts
  packages/rag/src/chunk-store/postgres/postgres-chunk-store.ts
  packages/rag/src/chunk-store/postgres/utils.ts
  packages/rag/src/database/index.ts
  packages/rag/src/database/types.ts
  packages/rag/src/database/utils.ts
  packages/rag/src/internal/column-mapping-utils.ts
  packages/rag/src/internal/create-column-mapping.ts
  packages/rag/src/internal/index.ts
  packages/rag/src/query-service/column-mapping.ts
  packages/rag/src/query-service/postgres/index.ts
Labels: Review effort 3/5

#1495 Remove .mcp.json configuration file
  .mcp.json
Labels: Review effort 1/5

#1496 Extract flow execution logic into separate runFlow function
  packages/giselle-engine/src/core/flows/create-and-run-flow.ts
  packages/giselle-engine/src/core/flows/run-flow.ts
Labels: Review effort 2/5

#1500 Reorganize development philosophy and add PR guidelines
  CLAUDE.md
Labels: Review effort 2/5

#1499 Add runFlow API and expose it through HTTP router
  packages/giselle-engine/src/core/flows/index.ts
  packages/giselle-engine/src/core/index.ts
  packages/giselle-engine/src/http/router.ts
Labels: Review effort 2/5

#1504 Remove "ui": "tui" from turbo.json
  turbo.json
Labels: Review effort 1/5

#1502 Replace mock tasks with real acts from database
  apps/studio.giselles.ai/app/stage/page.tsx
Labels: Review effort 3/5

#1396 fix: improve error messaging for duplicate email invitations
  apps/studio.giselles.ai/app/(main)/settings/team/invite-member-dialog.tsx
Labels: Review effort 4/5

#1503 Limit invitation actions to admin users only
  apps/studio.giselles.ai/app/(main)/settings/team/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/invitation-list-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-members-list.tsx
Labels: Review effort 2/5

#1508 Move stage files to (top) directory and add act details page with step view
  apps/studio.giselles.ai/app/stage/(top)/form.tsx
  apps/studio.giselles.ai/app/stage/(top)/helpers.ts
  apps/studio.giselles.ai/app/stage/(top)/layout.tsx
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/[stepId]/page.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/layout.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/page.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/nav.tsx
  apps/studio.giselles.ai/app/stage/acts/object.ts
  apps/studio.giselles.ai/package.json
  internal-packages/workflow-designer-ui/src/ui/generation-view.tsx
  pnpm-lock.yaml
Labels: Review effort 4/5

#1510 Rename jobs to sequences and operations to steps in workflow structure
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  internal-packages/workflow-designer-ui/src/header/ui/trigger-input-dialog/helpers.ts
  internal-packages/workflow-designer-ui/src/hooks/use-flow-controller.tsx
  packages/data-mod/src/mods/rename-action-to-operation.ts
  packages/data-type/src/workflow/index.ts
  packages/giselle-engine/src/core/flows/create-and-run-flow.ts
  packages/giselle-engine/src/core/flows/run-flow.ts
  packages/giselle-engine/src/core/github/event-handlers.ts
  packages/workflow-utils/src/build-workflow-from-node.test.ts
  packages/workflow-utils/src/build-workflow-from-node.ts
  packages/workflow-utils/src/helper.test.ts
  packages/workflow-utils/src/helper.ts
Labels: Review effort 4/5

#1511 Rename FlowRun to Act throughout the codebase
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/migrations/0039_wooden_tyrannus.sql
  apps/studio.giselles.ai/migrations/meta/0039_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
  internal-packages/workflow-designer-ui/src/editor/run-history/run-history-table.tsx
  internal-packages/workflow-designer-ui/src/hooks/use-flow-controller.tsx
  packages/data-type/src/generation/context.ts
  packages/giselle-engine/src/core/files/utils.ts
  packages/giselle-engine/src/core/flows/act-flow.ts
  packages/giselle-engine/src/core/flows/act/object.ts
  packages/giselle-engine/src/core/flows/act/patch-object.ts
  packages/giselle-engine/src/core/flows/act/paths.ts
  packages/giselle-engine/src/core/flows/create-act.ts
  packages/giselle-engine/src/core/flows/create-and-act-flow.ts
  packages/giselle-engine/src/core/flows/get-workspace-flow-runs.ts
  packages/giselle-engine/src/core/flows/index.ts
  packages/giselle-engine/src/core/flows/patch-run.ts
  packages/giselle-engine/src/core/flows/resolve-trigger.ts
  packages/giselle-engine/src/core/flows/run/paths.ts
  packages/giselle-engine/src/core/generations/internal/use-generation-executor.ts
  packages/giselle-engine/src/core/github/event-handlers.test.ts
  packages/giselle-engine/src/core/github/event-handlers.ts
  packages/giselle-engine/src/core/github/handle-webhook-v2.ts
  packages/giselle-engine/src/core/index.ts
  packages/giselle-engine/src/http/router.ts
Labels: Review effort 4/5

#1513 Rename actFlow to startAct and reorganize acts directory structure
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  packages/giselle-engine/src/core/acts/create-act.ts
  packages/giselle-engine/src/core/acts/create-and-start-act.ts
  packages/giselle-engine/src/core/acts/get-workspace-acts.ts
  packages/giselle-engine/src/core/acts/index.ts
  packages/giselle-engine/src/core/acts/object/index.ts
  packages/giselle-engine/src/core/acts/object/patch-object.ts
  packages/giselle-engine/src/core/acts/object/paths.ts
  packages/giselle-engine/src/core/acts/patch-act.ts
  packages/giselle-engine/src/core/acts/start-act.ts
  packages/giselle-engine/src/core/flows/index.ts
  packages/giselle-engine/src/core/github/event-handlers.test.ts
  packages/giselle-engine/src/core/github/event-handlers.ts
  packages/giselle-engine/src/core/github/handle-webhook-v2.ts
  packages/giselle-engine/src/core/index.ts
  packages/giselle-engine/src/http/router.ts
Labels: Review effort 3/5

#1515 Rename generation methods to include "Runner" suffix for clarity
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/header/ui/trigger-input-dialog/helpers.ts
  internal-packages/workflow-designer-ui/src/hooks/use-flow-controller.tsx
  packages/giselle-engine/src/react/generations/contexts/generation-runner-system.tsx
  packages/giselle-engine/src/react/generations/hooks/use-node-generations.ts
Labels: Review effort 2/5

#1517 feat: add query result limit and similarity threshold controls
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/settings-panel.tsx
  internal-packages/workflow-designer-ui/src/ui/query-result-view.tsx
  packages/data-type/src/node/operations/query.ts
  packages/giselle-engine/src/core/operations/execute-query.ts
  packages/giselle-engine/src/utils/node-factories.ts
  packages/rag/src/query-service/postgres/index.ts
  packages/rag/src/query-service/types.ts
Labels: Review effort 3/5, Possible security concern

#1519 Add addGenerationRunner method to GenerationRunnerSystemContext
  packages/giselle-engine/src/react/generations/contexts/generation-runner-system.tsx
Labels: Review effort 2/5

#1498 chore(studio): migrate to githubRepositoryContentStatus table with type-safe metadata
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/data.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/diagnostic-modal.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-list.tsx
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/lib/vector-stores/github/get-github-vector-stores.ts
  apps/studio.giselles.ai/lib/vector-stores/github/index.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/fetch-ingest-targets.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/ingest-github-blobs.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/process-repository.ts
  apps/studio.giselles.ai/lib/vector-stores/github/types.ts
  apps/studio.giselles.ai/migrations/0041_friendly_jack_flag.sql
  apps/studio.giselles.ai/migrations/meta/0041_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
  apps/studio.giselles.ai/scripts/20250722-db-patch-migrate-github-status-to-content-status.ts
Labels: Review effort 4/5

#1526 Remove unused ActId import and add experimental_storage flag
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
Labels: Review effort 2/5

#1533 Move Act types from engine/acts/object to concepts/act directory
  packages/giselle/src/engine/acts/create-act.ts
  packages/giselle/src/engine/acts/create-and-start-act.ts
  packages/giselle/src/engine/acts/get-workspace-acts.ts
  packages/giselle/src/engine/acts/index.ts
  packages/giselle/src/engine/acts/object/index.ts
  packages/giselle/src/engine/acts/object/patch-object.ts
  packages/giselle/src/engine/acts/object/paths.ts
  packages/giselle/src/engine/acts/patch-act.ts
  packages/giselle/src/engine/acts/start-act.ts
  packages/giselle/src/engine/index.ts
  packages/giselle/src/http/router.ts
Labels: Review effort 2/5

#1536 Move workflow types from data-type to giselle/concepts/workflow
  packages/data-type/src/index.ts
  packages/giselle/src/concepts/workflow/index.ts
  packages/giselle/src/engine/error.ts
  packages/giselle/src/engine/flows/build-workflow-from-trigger.ts
  packages/giselle/src/engine/index.ts
  packages/giselle/src/engine/utils/workflow/build-workflow-from-node.test.ts
  packages/giselle/src/engine/utils/workflow/build-workflow-from-node.ts
  packages/giselle/src/engine/utils/workflow/helper.test.ts
  packages/giselle/src/engine/utils/workflow/helper.ts
Labels: Review effort 2/5

#1537 Simplify Act navigation UI and align status terminology
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/nav.tsx
  packages/giselle/src/concepts/act.ts
  packages/giselle/src/engine/acts/create-act.ts
  packages/giselle/src/engine/acts/start-act.ts
Labels: Review effort 3/5

#1527 fix(studio): fix inconsist column name
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/migrations/0042_material_colonel_america.sql
  apps/studio.giselles.ai/migrations/meta/0042_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
Labels: Review effort 2/5

#1539 Update patchAct to use experimental_storage.setJson
  packages/giselle/src/engine/acts/patch-act.ts
Labels: Review effort 2/5

#1542 Redesign manual trigger configured view UI for improved readability
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/ui/configured-views/manual-trigger-configured-view.tsx
Labels: Review effort 2/5

#1543 Redesign manual trigger properties panel with improved UI and type selection
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/manual-trigger/manual-trigger-properties-panel.tsx
Labels: Review effort 3/5

#1546 Add Toast component to playground UI
  apps/playground/app/ui/layout.tsx
  apps/playground/app/ui/toast/page.tsx
Labels: Review effort 2/5

#1548 Add revalidatePath after act creation to refresh stage page
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
Labels: Review effort 2/5

#1550 Add prevd and vd scripts for Vercel development workflow
  knip.ts
  package.json
Labels: Review effort 1/5

#1553 Remove unused useVectorStore import from toolbar component
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
Labels: Review effort 1/5

#1554 Fix Select component to use min-width for long options
  apps/playground/app/ui/select/page.tsx
  internal-packages/ui/components/select.tsx
Labels: Review effort 2/5

#1559 Standardize dropdown and select components to use value/label pattern with icon support
  apps/playground/app/ui/dropdown-menu/page.tsx
  apps/playground/app/ui/select/page.tsx
  apps/studio.giselles.ai/app/stage/(top)/form.tsx
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  internal-packages/ui/components/dropdown-menu.tsx
  internal-packages/ui/components/select.tsx
  internal-packages/workflow-designer-ui/src/editor/data-source/data-source-table.tsx
  internal-packages/workflow-designer-ui/src/editor/data-source/provider/github/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/ui/github-action-configured-view.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/prompt-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/prompt-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/postgres.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/manual-trigger/manual-trigger-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-header.tsx
Labels: Review effort 4/5

#1561 Add toast notification when workflow is submitted with cancel option
  .claude/agents/ts-coder.md
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/trigger-input-dialog/dialog.tsx
  internal-packages/workflow-designer-ui/src/hooks/use-act-controller.tsx
  packages/giselle/src/engine/acts/index.ts
  packages/giselle/src/engine/acts/shared/act-execution-utils.ts
  packages/giselle/src/engine/acts/start-act.ts
  packages/giselle/src/engine/index.ts
  packages/giselle/src/react/act/index.ts
  packages/giselle/src/react/act/use-act-controller.tsx
  packages/giselle/src/react/index.ts
Labels: Review effort 4/5

#1528 feat(studio): add GitHub PR ingestion pipeline
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/fetch-ingest-targets.ts
  apps/studio.giselles.ai/app/api/vector-stores/github/ingest/route.ts
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/lib/vector-stores/github/index.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/blobs/chunk-store.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/blobs/ingest-github-blobs.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/build-octokit.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/error-handling.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/process-repository.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/pull-requests/chunk-store.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/pull-requests/ingest-github-pull-requests.ts
  apps/studio.giselles.ai/lib/vector-stores/github/query/service.ts
  apps/studio.giselles.ai/lib/vector-stores/github/types.ts
  packages/github-tool/src/document-loaders/pull-requests/loader.ts
  packages/rag/src/chunk-store/postgres/utils.ts
Labels: Review effort 4/5

#1562 Simplify act execution utilities with cleaner status transitions and timing logic
  packages/giselle/src/engine/acts/shared/act-execution-utils.ts
Labels: Review effort 3/5

#1563 Add tests for act execution utilities with sequence and step handling
  packages/giselle/src/engine/acts/shared/act-execution-utils.test.ts
  packages/giselle/src/engine/acts/shared/act-execution-utils.ts
Labels: Review effort 3/5

#1530 feat(studio): add Pull Request content type management to Vector Stores
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/configure-sources-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item-blob-only.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-list.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-registration-dialog.tsx
  apps/studio.giselles.ai/flags.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/process-repository.ts
Labels: Review effort 4/5

#1565 feat(studio): add GitHub Pull Request vector store UI implementation
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/lib/vector-stores/github/get-github-pull-request-vector-stores.ts
  apps/studio.giselles.ai/lib/vector-stores/github/index.ts
  internal-packages/workflow-designer-ui/src/editor/lib/use-github-vector-store-status.ts
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/github-node-info.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  internal-packages/workflow-designer-ui/src/ui/query-result-view.tsx
  packages/giselle/src/react/feature-flags/context.ts
  packages/giselle/src/react/vector-store/context.tsx
  packages/giselle/src/react/workspace/provider.tsx
  packages/giselle/src/utils/node-default-name.ts
Labels: Review effort 4/5

#1568 add-exists-method-gisellestorage
  packages/giselle/src/engine/experimental_storage/fs-storage-driver.ts
  packages/giselle/src/engine/experimental_storage/memory-storage-driver.ts
  packages/giselle/src/engine/experimental_storage/types.ts
  packages/supabase-driver/src/storage/supabase-storage-driver.ts
Labels: Review effort 2/5

#1570 fix(rag): Reduce default maxChars to 6000 for embedding model compatibility
  packages/rag/src/chunker/index.ts
Labels: Review effort 1/5

#1566 Add_workspace_node_grouping_utility_with_test_fixtures_and_test_cases
  apps/studio.giselles.ai/app/(main)/apps/components/searchable-agent-list.tsx
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  internal-packages/ui/components/dropdown-menu.tsx
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/trigger-input-dialog/dialog.tsx
  packages/data-type/src/node/base.ts
  packages/giselle/src/engine/acts/create-act.ts
  packages/giselle/src/engine/experimental_storage/fs-storage-driver.ts
  packages/giselle/src/engine/generations/utils.ts
  packages/giselle/src/engine/github/event-handlers.test.ts
  packages/giselle/src/engine/github/event-handlers.ts
  packages/giselle/src/engine/utils/__fixtures__/workspace1.json
  packages/giselle/src/engine/utils/__fixtures__/workspace2.json
  packages/giselle/src/engine/utils/__fixtures__/workspace3.json
  packages/giselle/src/engine/utils/__fixtures__/workspace4.json
  packages/giselle/src/engine/utils/workflow/build-workflow-from-node.test.ts
  packages/giselle/src/engine/utils/workflow/slice-graph-from-node.test.ts
  packages/giselle/src/engine/utils/workflow/test/test-data.ts
  packages/giselle/src/engine/utils/workspace/__fixtures__/workspace1.ts
  packages/giselle/src/engine/utils/workspace/group-nodes.test.ts
  packages/giselle/src/engine/utils/workspace/group-nodes.ts
  packages/giselle/src/react/act/index.ts
  packages/giselle/src/react/act/use-act-controller.tsx
  packages/giselle/src/react/act/use-node-groups.ts
  packages/giselle/src/react/flow-trigger/index.ts
  packages/giselle/src/react/workspace/provider.tsx
Labels: Review effort 4/5

#1574 Revert "Add_workspace_node_grouping_utility_with_test_fixtures_and_test_cases"
  apps/studio.giselles.ai/app/(main)/apps/components/searchable-agent-list.tsx
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  internal-packages/ui/components/dropdown-menu.tsx
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/trigger-input-dialog/dialog.tsx
  packages/data-type/src/node/base.ts
  packages/giselle/src/engine/acts/create-act.ts
  packages/giselle/src/engine/experimental_storage/fs-storage-driver.ts
  packages/giselle/src/engine/generations/utils.ts
  packages/giselle/src/engine/github/event-handlers.test.ts
  packages/giselle/src/engine/github/event-handlers.ts
  packages/giselle/src/engine/utils/workflow/build-workflow-from-node.test.ts
  packages/giselle/src/engine/utils/workflow/slice-graph-from-node.test.ts
  packages/giselle/src/engine/utils/workflow/test/fixtures/workspace1.json
  packages/giselle/src/engine/utils/workflow/test/fixtures/workspace2.json
  packages/giselle/src/engine/utils/workflow/test/fixtures/workspace3.json
  packages/giselle/src/engine/utils/workflow/test/fixtures/workspace4.json
  packages/giselle/src/engine/utils/workflow/test/test-data.ts
  packages/giselle/src/engine/utils/workspace/__fixtures__/workspace1.ts
  packages/giselle/src/engine/utils/workspace/group-nodes.test.ts
  packages/giselle/src/engine/utils/workspace/group-nodes.ts
  packages/giselle/src/react/act/index.ts
  packages/giselle/src/react/act/use-act-controller.tsx
  packages/giselle/src/react/act/use-node-groups.ts
  packages/giselle/src/react/flow-trigger/index.ts
  packages/giselle/src/react/workspace/provider.tsx
Labels: Review effort 4/5

#1573 Fix query result tabs layout to prevent wrapping
  internal-packages/workflow-designer-ui/src/ui/query-result-view.tsx
Labels: Review effort 2/5

#1571 Unify GitHub vector store nodes for code and pull requests
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/lib/vector-stores/github/get-github-pull-request-vector-stores.ts
  apps/studio.giselles.ai/lib/vector-stores/github/get-github-repository-indexes.ts
  apps/studio.giselles.ai/lib/vector-stores/github/get-github-vector-stores.ts
  apps/studio.giselles.ai/lib/vector-stores/github/index.ts
  internal-packages/workflow-designer-ui/src/editor/lib/use-github-vector-store-status.ts
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/github-node-info.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/github-repository-badge-with-type.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/index.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/index.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  internal-packages/workflow-designer-ui/src/icons/node/index.tsx
  packages/data-type/src/node/variables/vector-store.ts
  packages/giselle/src/concepts/generation/output.ts
  packages/giselle/src/data-mod/index.ts
  packages/giselle/src/data-mod/mods/unify-github-vector-store.test.ts
  packages/giselle/src/data-mod/mods/unify-github-vector-store.ts
  packages/giselle/src/engine/operations/execute-query.ts
  packages/giselle/src/engine/vector-store/types.ts
  packages/giselle/src/react/vector-store/context.tsx
  packages/giselle/src/utils/node-default-name.ts
Labels: Review effort 4/5

#1580 refactor-run-button-logic
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
Labels: Review effort 4/5

#1581 refactor(ui): simplify dropdown menu class handling and remove unused renderItem
  internal-packages/ui/components/dropdown-menu.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/prompt-panel.tsx
Labels: Review effort 2/5
