Repository giselles-ai/giselle, pull requests merged in 2025-08, with the labels that each got.

#1589 refactor: extract buildLevels function and improve node grouping logic
  packages/giselle/src/engine/acts/create-act.ts
  packages/giselle/src/engine/github/event-handlers.test.ts
  packages/giselle/src/engine/github/event-handlers.ts
  packages/giselle/src/engine/utils/__fixtures__/two-trigger.ts
  packages/giselle/src/engine/utils/build-levels.test.ts
  packages/giselle/src/engine/utils/build-levels.ts
  packages/giselle/src/engine/utils/workspace/group-nodes.test.ts
  packages/giselle/src/engine/utils/workspace/group-nodes.ts
  packages/giselle/src/react/act/use-node-groups.ts
Labels: Review effort 4/5

#1598 fix typo `Giselles` -> `Giselle`
  .claude/agents/ux-guardian.md
Labels: Review effort 1/5

#1597 Go ai sdk v5
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  docs/packages-license.md
  internal-packages/workflow-designer-ui/src/editor/data-source/data-source-table.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/generation-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/model/anthropic.tsx
  internal-packages/workflow-designer-ui/src/ui/generation-view.tsx
  packages/data-type/src/node/operations/text-generation.ts
  packages/giselle/package.json
  packages/giselle/src/concepts/act.ts
  packages/giselle/src/concepts/generation/index.ts
  packages/giselle/src/concepts/generation/output.ts
  packages/giselle/src/engine/acts/create-act.ts
  packages/giselle/src/engine/acts/object/patch-creators.test.ts
  packages/giselle/src/engine/acts/object/patch-creators.ts
  packages/giselle/src/engine/acts/object/patch-object.test.ts
  packages/giselle/src/engine/acts/shared/act-execution-utils.test.ts
  packages/giselle/src/engine/acts/start-act.ts
  packages/giselle/src/engine/data-source/create-data-source.ts
  packages/giselle/src/engine/data-source/types/object.ts
  packages/giselle/src/engine/experimental_storage/fs-storage-driver.ts
  packages/giselle/src/engine/experimental_storage/memory-storage-driver.ts
  packages/giselle/src/engine/experimental_storage/types.ts
  packages/giselle/src/engine/experimental_vector-store/types/object.ts
  packages/giselle/src/engine/generations/generate-image.ts
  packages/giselle/src/engine/generations/generate-text.ts
  packages/giselle/src/engine/generations/internal/use-generation-executor.ts
  packages/giselle/src/engine/generations/tools/postgres.ts
  packages/giselle/src/engine/generations/utils.ts
  packages/giselle/src/engine/telemetry/index.ts
  packages/giselle/src/http/router.ts
  packages/giselle/src/react/generations/contexts/generation-runner-system.tsx
  packages/giselle/src/react/generations/generation-runner.tsx
  packages/github-tool/src/tools.ts
  packages/language-model/src/anthropic.ts
  packages/language-model/src/costs/index.test.ts
  packages/language-model/src/costs/index.ts
  packages/rag/src/query-service/postgres/index.ts
  packages/supabase-driver/src/storage/supabase-storage-driver.ts
  packages/vector-store-adapters/src/openai/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 4/5

#1599 fix(start-act): remove explicit WritableStream return type for compatibility
  packages/giselle/src/engine/acts/start-act.ts
Labels: Review effort 1/5

#1600 Remove pullRequestVectorStoreFlag
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item-blob-only.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-list.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-registration-dialog.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  packages/giselle/src/react/feature-flags/context.ts
  packages/giselle/src/react/workspace/provider.tsx
Labels: Review effort 2/5

#1602 feat(nav): set default open sequences in accordion based on act data
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/nav.tsx
Labels: Review effort 2/5

#1603 feat: add patch queue system to batch and merge patch operations
  packages/giselle/src/engine/acts/patch-queue.ts
  packages/giselle/src/engine/acts/shared/act-execution-utils.ts
  packages/giselle/src/engine/acts/start-act.ts
Labels: Review effort 4/5

#1605 feat: replace reload form with ReloadButton component using transition
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  apps/studio.giselles.ai/app/stage/(top)/reload-button.tsx
Labels: Review effort 2/5

#1613 docs: add model field to ts-coder agent configuration
  .claude/agents/ts-coder.md
Labels: Review effort 1/5

#1619 feat-sidebar-nav-layout-updates
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/[stepId]/page.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/[stepId]/ui/step-layout.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/layout.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/loading.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/nav-skelton.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/nav.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/sidebar.tsx
  packages/giselle/src/react/act/index.ts
Labels: Review effort 3/5

#1621 fix(next-giselle-engine): handle Zod validation errors in JSON router input
  packages/giselle/src/next/next-giselle-engine.ts
Labels: Review effort 2/5, Possible security concern

#1617 feat: Add PR context to RAG query results for comment/diff chunks
  apps/studio.giselles.ai/lib/vector-stores/github/query/pull-requests/pr-context-utils.ts
  apps/studio.giselles.ai/lib/vector-stores/github/query/pull-requests/schema.ts
  apps/studio.giselles.ai/lib/vector-stores/github/query/pull-requests/service.ts
  internal-packages/workflow-designer-ui/src/ui/query-result-view.tsx
  packages/giselle/src/concepts/generation/output.ts
  packages/giselle/src/engine/generations/utils.ts
  packages/giselle/src/engine/operations/execute-query.ts
  packages/rag/src/query-service/postgres/index.ts
  packages/rag/src/query-service/types.ts
Labels: Review effort 4/5, Possible security concern

#1452 feat: migrate to Stripe Basil API (v18.3.0)
  apps/studio.giselles.ai/app/webhooks/stripe/billing-meter/route.ts
  apps/studio.giselles.ai/app/webhooks/stripe/handle-invoice-creation.ts
  apps/studio.giselles.ai/app/webhooks/stripe/route.ts
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/package.json
  apps/studio.giselles.ai/scripts/20250116-db-patch-add-customer-id-to-subscriptions.ts
  apps/studio.giselles.ai/services/external/stripe/actions/upsert-subscription.ts
  apps/studio.giselles.ai/services/external/stripe/config.ts
  docs/packages-license.md
  pnpm-lock.yaml
Labels: Review effort 4/5

#1622 feat(web-search): add User-Agent header for web page fetching
  packages/web-search/src/self-made.ts
Labels: Review effort 2/5, Possible security concern

#1629 feat: remove GitHub forkRepository tool
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github.tsx
  packages/github-tool/src/tools.ts
Labels: Review effort 2/5

#1624 feat(stripe): populate customer_id when upserting subscriptions
  apps/studio.giselles.ai/services/external/stripe/actions/upsert-subscription.ts
Labels: Review effort 2/5

#1607 Feature/UI list adjustment
  apps/playground/app/ui/status-badge/page.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/searchable-agent-list.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  internal-packages/ui/components/select.tsx
  internal-packages/ui/components/status-badge.tsx
  internal-packages/ui/style.css
  internal-packages/workflow-designer-ui/src/editor/node/ui/github-node-info.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/github-repository-badge-with-type.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/github-repository-badge.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/index.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
Labels: Review effort 3/5

#1632 fix(giselle): add stop condition to limit generation steps in text generation
  packages/giselle/src/engine/generations/generate-text.ts
Labels: Review effort 2/5

#1634 Allow gho_ GitHub tokens
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github.tsx
Labels: codex, Review effort 2/5

#1636 feat: add support for claude-opus-4-1-20250805 model
  packages/language-model/src/anthropic.test.ts
  packages/language-model/src/anthropic.ts
  packages/language-model/src/costs/model-prices.ts
Labels: Review effort 2/5

#1637 feat: add GPT-5 model series support
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  packages/language-model/src/costs/model-prices.ts
  packages/language-model/src/openai.test.ts
  packages/language-model/src/openai.ts
Labels: Review effort 2/5

#1640 feat(gis): accept both experimental and standard github webhook route
  packages/giselle/src/next/next-giselle-engine.ts
Labels: Review effort 1/5, Possible security concern

#1647 refactor(giselle): simplify getLanguageModelProviders to return directly
  packages/giselle/src/engine/index.ts
  packages/giselle/src/http/router.ts
Labels: Review effort 1/5

#1651 fix: ensure staged triggers appear in /stage page after app duplication
  apps/studio.giselles.ai/app/(main)/apps/actions.ts
  packages/giselle/src/engine/workspaces/copy-workspace.ts
Labels: Review effort 3/5

#1652 refactor(giselle): remove Langfuse telemetry and unused helpers from
  packages/giselle/src/engine/generations/generate-image.ts
Labels: Review effort 2/5

#1662 feat-unify-generation-complete-and-telemetry
  apps/playground/giselle-engine.ts
  apps/studio.giselles.ai/app/giselle-engine.ts
  packages/giselle/src/engine/generations/generate-image.ts
  packages/giselle/src/engine/generations/generate-text.ts
  packages/giselle/src/engine/generations/internal/use-generation-executor.ts
  packages/giselle/src/engine/operations/execute-action.ts
  packages/giselle/src/engine/operations/execute-query.ts
  packages/giselle/src/engine/telemetry/index.ts
  packages/giselle/src/engine/types.ts
Labels: Review effort 3/5

#1655 feat(rag): add multi-embedding model support foundation
  packages/data-type/src/embedding/index.ts
  packages/data-type/src/index.ts
  packages/rag/README.md
  packages/rag/package.json
  packages/rag/src/embedder/ai-sdk-embedder.ts
  packages/rag/src/embedder/google.ts
  packages/rag/src/embedder/index.ts
  packages/rag/src/embedder/openai.ts
  packages/rag/src/embedder/profiles.ts
  packages/rag/src/ingest/pipeline.ts
  packages/rag/src/query-service/postgres/index.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#1658 fix: remove deleted agents from stage page
  apps/studio.giselles.ai/app/(main)/apps/actions.ts
Labels: Review effort 2/5

#1666 refactor(ts-coder): remove explicit return type annotations from simple functions
  .claude/agents/ts-coder.md
Labels: Review effort 2/5

#1654 Add copy button to Generator Node results in stage step view
  internal-packages/workflow-designer-ui/src/ui/generation-view.tsx
Labels: Review effort 2/5

#1649 Feat/adjust stage main screen
  apps/playground/app/ui/status-badge/page.tsx
  apps/studio.giselles.ai/app/stage/(top)/circular-carousel.module.css
  apps/studio.giselles.ai/app/stage/(top)/circular-carousel.tsx
  apps/studio.giselles.ai/app/stage/(top)/form.tsx
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  apps/studio.giselles.ai/app/stage/(top)/resizable-layout.tsx
  apps/studio.giselles.ai/app/stage/(top)/team-card.tsx
  apps/studio.giselles.ai/app/stage/layout.tsx
  apps/studio.giselles.ai/app/stage/ui/stage-sidebar.tsx
  apps/studio.giselles.ai/package.json
  internal-packages/ui/components/status-badge.tsx
  internal-packages/ui/style.css
  pnpm-lock.yaml
Labels: Review effort 3/5, Review effort 4/5

#1657 fix: Workflow doesn't run with only a Generator Node, despite 'submitted successfully' message
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
  packages/giselle/src/engine/acts/create-act.ts
  packages/giselle/src/react/act/use-act-controller.tsx
Labels: Review effort 2/5

#1684 feat(trace): add workspace team handling for github-app origins
  apps/studio.giselles.ai/app/giselle-engine.ts
  apps/studio.giselles.ai/lib/workspaces/get-workspace-team.ts
  apps/studio.giselles.ai/services/teams/utils.ts
Labels: Review effort 2/5

#1625 refactor(usage-based-billing): Remove isDelta field from user seat usage reports
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/migrations/0046_lush_shriek.sql
  apps/studio.giselles.ai/migrations/meta/0046_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
  apps/studio.giselles.ai/services/usage-based-billing/user-seat.ts
Labels: Review effort 2/5

#1590 feat: robust keyboard shortcuts with focus management for workflow designer
  docs/packages-license.md
  internal-packages/workflow-designer-ui/src/editor/context-menu/index.tsx
  internal-packages/workflow-designer-ui/src/editor/hooks/use-keyboard-shortcuts.ts
  internal-packages/workflow-designer-ui/src/editor/keyboard-shortcuts.tsx
  internal-packages/workflow-designer-ui/src/editor/node/index.ts
  internal-packages/workflow-designer-ui/src/editor/node/use-duplicate-node.ts
  internal-packages/workflow-designer-ui/src/editor/node/use-node-manipulation.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/file-node-properties-panel/file-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/v2-container.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/v2-placeholder.tsx
  packages/data-type/src/workspace/index.ts
  packages/giselle/src/engine/utils/__fixtures__/backward-traversal.ts
  packages/giselle/src/engine/utils/__fixtures__/group-nodes.ts
  packages/giselle/src/engine/utils/__fixtures__/two-trigger.ts
  packages/giselle/src/react/flow/context.tsx
  packages/giselle/src/react/flow/hooks/use-workspace-reducer.ts
  packages/giselle/src/react/flow/types.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 3/5, Review effort 4/5

#1692 feat-generation-act-indexes-update
  packages/giselle/src/concepts/path.ts
  packages/giselle/src/engine/generations/internal/act-generation-index-queue.ts
  packages/giselle/src/engine/generations/internal/generation-index-patches.ts
  packages/giselle/src/engine/generations/internal/get-act-generation-indexes.ts
  packages/giselle/src/engine/generations/internal/set-generation.ts
  packages/giselle/src/engine/generations/internal/use-generation-executor.ts
  packages/giselle/src/engine/index.ts
  packages/giselle/src/next/next-giselle-engine.test.ts
  packages/giselle/src/next/next-giselle-engine.ts
Labels: Review effort 3/5

#1695 feat(postgres): replace GitHub PAT UI with PostgreSQL connection UI and validation
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/postgres/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/postgres/postgres-validation.test.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/postgres/postgres-validation.ts
Labels: Review effort 2/5

#1698 feat(dialog): size prop to Dialog for responsive widths
  internal-packages/ui/components/dialog.tsx
Labels: Review effort 2/5

#1697 refactor: standardize embedding column names as constants
  packages/rag/src/chunk-store/column-mapping.ts
  packages/rag/src/chunk-store/postgres/utils.test.ts
  packages/rag/src/chunk-store/postgres/utils.ts
  packages/rag/src/database/constants.ts
  packages/rag/src/query-service/postgres/index.ts
Labels: Review effort 2/5

#1694 Feat/improve stage acts detail page
  apps/studio.giselles.ai/app/globals.css
  apps/studio.giselles.ai/app/stage/acts/[actId]/[stepId]/page.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/[stepId]/ui/step-layout.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/actions.ts
  apps/studio.giselles.ai/app/stage/acts/[actId]/layout.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/lib/data.ts
  apps/studio.giselles.ai/app/stage/acts/[actId]/lib/utils.ts
  apps/studio.giselles.ai/app/stage/acts/[actId]/mobile-scroll.css
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/sidebar.tsx
  apps/studio.giselles.ai/app/stage/layout.tsx
  apps/studio.giselles.ai/package.json
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/index.ts
  internal-packages/workflow-designer-ui/src/ui/generation-view.tsx
  pnpm-lock.yaml
Labels: Review effort 3/5

#1693 feat: Add embedding profile status management for GitHub repository ingestion
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/lib/vector-stores/github/embedding-profiles.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/blobs/ingest-github-blobs.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/process-repository.ts
  apps/studio.giselles.ai/lib/vector-stores/github/ingest/pull-requests/ingest-github-pull-requests.ts
  apps/studio.giselles.ai/migrations/0047_hot_chamber.sql
  apps/studio.giselles.ai/migrations/meta/0047_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
Labels: Review effort 3/5

#1702 feat: Implement download functionality for desktop and mobile act det…
  apps/studio.giselles.ai/app/stage/acts/[actId]/[stepId]/page.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/[stepId]/ui/step-layout.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/loading.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/mobile-actions.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/sidebar.tsx
Labels: Review effort 2/5

#1691 feat(workspace): enable creation of multiple sample workspaces
  apps/playground/app/page.tsx
  apps/playground/giselle-engine.ts
  apps/studio.giselles.ai/app/giselle-engine.ts
  apps/studio.giselles.ai/services/accounts/actions/initialize-account.ts
  packages/giselle/src/engine/index.ts
  packages/giselle/src/engine/types.ts
  packages/giselle/src/engine/workspaces/create-sample-workspace.ts
  packages/giselle/src/http/router.ts
  packages/github-tool/turbo.json
  turbo.json
Labels: Review effort 2/5

#1703 chore(deps): bump React and @types to 19.1.x for consistency
  docs/packages-license.md
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 1/5

#1708 fix: generate unique IDs for sample workspace elements
  packages/giselle/src/engine/workspaces/create-sample-workspace.ts
Labels: Review effort 2/5

#1710 Fix TeamAvatarImage sizing and display team icons in user teams list
  apps/studio.giselles.ai/app/(main)/settings/account/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/user-teams.tsx
  apps/studio.giselles.ai/services/teams/components/team-avatar-image.tsx
Labels: Review effort 2/5

#1715 refactor-agent-list-query-types
  apps/studio.giselles.ai/app/(main)/apps/components/agent-card.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/agent-grid.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/constants.ts
  apps/studio.giselles.ai/app/(main)/apps/components/light-overlay.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/searchable-agent-list.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/types.ts
  apps/studio.giselles.ai/app/(main)/apps/components/use-light-tracking.ts
  apps/studio.giselles.ai/app/(main)/apps/components/utils.ts
  apps/studio.giselles.ai/app/(main)/apps/page.tsx
Labels: Review effort 2/5

#1714 Feat/stage tasks panel
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  apps/studio.giselles.ai/app/stage/(top)/reload-button.tsx
  apps/studio.giselles.ai/app/stage/(top)/services.ts
Labels: Review effort 2/5

#1717 feat(sidebar switch to Suspense use() for async sidebar data
  apps/studio.giselles.ai/app/stage/layout.tsx
  apps/studio.giselles.ai/app/stage/query.ts
  apps/studio.giselles.ai/app/stage/ui/stage-sidebar.tsx
Labels: Review effort 2/5

#1711 Feat/stage acts adjustments
  apps/studio.giselles.ai/app/stage/acts/components/filterable-acts-list.tsx
  apps/studio.giselles.ai/app/stage/acts/page.tsx
  apps/studio.giselles.ai/app/stage/acts/types/index.ts
Labels: Review effort 3/5

#1719 refactor: reorganize repository index actions for multi-embedding support
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/configure-sources-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-list.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-registration-dialog.tsx
Labels: Review effort 3/5

#1722 refactor(page): remove act metadata fetch input extraction to simplify page data
  apps/studio.giselles.ai/app/stage/acts/page.tsx
Labels: Review effort 2/5

#1726 fix(github-tool): handle repository not found errors in pull request ingest
  packages/github-tool/src/document-loaders/pull-requests/fetchers.ts
Labels: Review effort 2/5

#1690 feat: add embedding profile selection in VectorStoreNode
  apps/studio.giselles.ai/lib/vector-stores/github/get-github-repository-indexes.ts
  internal-packages/workflow-designer-ui/src/editor/lib/use-github-vector-store-status.ts
  internal-packages/workflow-designer-ui/src/editor/node/ui/github-node-info.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
  packages/data-type/src/embedding/index.ts
  packages/data-type/src/node/variables/vector-store.ts
  packages/giselle/src/engine/operations/execute-query.ts
  packages/giselle/src/react/vector-store/context.tsx
Labels: Review effort 3/5

#1729 refactor: eliminate hardcoded embedding profile IDs
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/scripts/20250815-db-patch-add-default-embedding-profiles.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
  packages/data-type/src/embedding/index.ts
  packages/data-type/src/embedding/profiles.ts
  packages/giselle/src/engine/operations/execute-query.ts
  packages/rag/src/chunk-store/postgres/utils.test.ts
  packages/rag/src/ingest/pipeline.test.ts
Labels: Review effort 2/5

#1732 feat-responsive-nav-rail-sidebar
  apps/studio.giselles.ai/app/globals.css
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  apps/studio.giselles.ai/app/stage/layout.tsx
  apps/studio.giselles.ai/app/stage/query.ts
  apps/studio.giselles.ai/app/stage/ui/mobile-header.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/AGENTS.md
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/index.ts
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/menu-button.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-items.ts
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-list-item.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-list.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-rail-collapsed.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-rail-container.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-rail-contents-container.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-rail-expanded.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-rail-footer-menu.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-rail-footer.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-rail-header.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-rail.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/types.ts
  apps/studio.giselles.ai/app/stage/ui/stage-sidebar.tsx
  apps/studio.giselles.ai/package.json
  internal-packages/ui/components/button.tsx
  internal-packages/ui/components/dropdown-menu.tsx
  pnpm-lock.yaml
Labels: Review effort 3/5

#1740 fix: correct frequency penalty label
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/model/openai.tsx
Labels: codex, Review effort 1/5

#1748 feat-add-ai-gateway-featureflags
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/giselle-engine.ts
  apps/studio.giselles.ai/app/stage/(top)/actions.ts
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  packages/giselle/package.json
  packages/giselle/src/engine/acts/create-and-start-act.ts
  packages/giselle/src/engine/acts/start-act.ts
  packages/giselle/src/engine/generations/generate-text.ts
  packages/giselle/src/engine/generations/internal/use-generation-executor.ts
  packages/giselle/src/engine/github/event-handlers.ts
  packages/giselle/src/engine/index.ts
  packages/giselle/src/engine/types.ts
  packages/giselle/src/http/router.ts
  packages/giselle/src/react/feature-flags/context.ts
  packages/giselle/src/react/generations/generation-runner.tsx
  packages/giselle/src/react/workspace/provider.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 3/5

#1626 refactor(workflow-designer): improve keyboard shortcut focus management
  internal-packages/workflow-designer-ui/src/editor/components/keyboard-shortcuts.tsx
  internal-packages/workflow-designer-ui/src/editor/hooks/use-keyboard-shortcuts.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
Labels: Review effort 2/5, Review effort 3/5, Review effort 4/5

#1750 feat(generator-node): add copy button for error messages
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/generation-panel.tsx
Labels: Review effort 2/5

#1759 refactor(giselle): remove unused telemetry from image generation
  packages/giselle/src/engine/generations/generate-image.ts
  packages/giselle/src/engine/generations/types.ts
  packages/giselle/src/engine/index.ts
  packages/giselle/src/http/router.ts
  packages/giselle/src/react/generations/generation-runner.tsx
Labels: Review effort 2/5

#1754 feat(rag): add embedding telemetry foundation with callbacks and metrics
  packages/data-type/src/embedding/index.ts
  packages/data-type/src/embedding/profiles.ts
  packages/langfuse/package.json
  packages/langfuse/src/index.ts
  packages/langfuse/src/trace-embedding.ts
  packages/rag/src/embedder/ai-sdk-embedder.test.ts
  packages/rag/src/embedder/ai-sdk-embedder.ts
  packages/rag/src/embedder/google.ts
  packages/rag/src/embedder/index.ts
  packages/rag/src/embedder/openai.ts
  packages/rag/src/embedder/profiles.ts
  packages/rag/src/embedder/types.ts
  packages/rag/src/ingest/pipeline.ts
  packages/rag/src/query-service/postgres/index.ts
  packages/rag/src/query-service/types.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#1760 feat(giselle): add resumableGeneration flag through engine to UI and types
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/stage/(top)/actions.ts
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/flags.ts
  packages/giselle/src/concepts/generation/index.ts
  packages/giselle/src/engine/acts/create-and-start-act.ts
  packages/giselle/src/engine/acts/start-act.ts
  packages/giselle/src/engine/generations/generate-text.ts
  packages/giselle/src/engine/generations/internal/use-generation-executor.ts
  packages/giselle/src/engine/github/event-handlers.ts
  packages/giselle/src/engine/index.ts
  packages/giselle/src/http/router.ts
  packages/giselle/src/react/feature-flags/context.ts
  packages/giselle/src/react/generations/generation-runner.tsx
  packages/giselle/src/react/workspace/provider.tsx
Labels: Review effort 2/5

#1755 feat(language-model,langfuse): add embedding pricing tables and total-only cost reporting
  packages/langfuse/src/trace-embedding.ts
  packages/language-model/src/costs/embedding-costs.test.ts
  packages/language-model/src/costs/index.ts
  packages/language-model/src/costs/model-prices.ts
Labels: Review effort 2/5

#1763 fix(studio): enforce max avatar image size limit
  apps/studio.giselles.ai/app/(main)/settings/components/profile-edit-modal.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-profile-edit-modal.tsx
  apps/studio.giselles.ai/app/(main)/settings/utils/avatar-upload.ts
Labels: Review effort 1/5

#1762 Fix GPT-5 reasoning item error by removing step count limit
  packages/giselle/src/engine/generations/generate-text.ts
Labels: Review effort 2/5

#1766 Settings: Allow saving only when the form is valid
  apps/studio.giselles.ai/app/(main)/settings/components/profile-edit-modal.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-profile-edit-modal.tsx
Labels: Review effort 2/5

#1769 feat(language-model): restructure OpenAI models to GPT-5 series only
  packages/language-model/src/costs/index.test.ts
  packages/language-model/src/costs/model-prices.ts
  packages/language-model/src/openai.test.ts
  packages/language-model/src/openai.ts
Labels: Review effort 2/5
