Repository giselles-ai/giselle, pull requests merged in 2025-10, with the labels that each got.

#1892 feat(studio): add text chunking for document ingestion
  apps/studio.giselles.ai/lib/vector-stores/document/ingest/chunk-text.ts
  apps/studio.giselles.ai/lib/vector-stores/document/ingest/ingest-document.ts
Labels: Review effort 2/5

#1853 Handle agent deletion errors safely
  apps/studio.giselles.ai/app/(main)/apps/actions.ts
  apps/studio.giselles.ai/app/(main)/apps/components/delete-agent-button.tsx
Labels: Review effort 2/5

#1898 feat(vector-store): implement dual-path document ingestion with atomic claim
  apps/studio.giselles.ai/app/api/vector-stores/document/[documentVectorStoreId]/documents/route.ts
  apps/studio.giselles.ai/app/api/vector-stores/document/ingest/fetch-ingest-targets.ts
  apps/studio.giselles.ai/app/api/vector-stores/document/ingest/route.ts
  apps/studio.giselles.ai/lib/vector-stores/document/ingest/ingest-document.ts
  apps/studio.giselles.ai/vercel.json
Labels: Review effort 2/5, Review effort 3/5

#1901 feat: add document vector store type definitions
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/github/index.tsx
  packages/data-type/src/node/variables/vector-store.ts
  packages/giselle/src/engine/operations/execute-query.ts
  packages/giselle/src/engine/vector-store/types.ts
  packages/giselle/src/utils/node-default-name.ts
Labels: Review effort 2/5

#1902 feat: add Document Vector Store node factory and UI integration
  apps/playground/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  packages/giselle/src/react/feature-flags/context.ts
  packages/giselle/src/react/workspace/provider.tsx
  packages/giselle/src/utils/node-factories.ts
Labels: Review effort 2/5

#1905 fix: sanitize NUL characters in RAG document processing
  packages/github-tool/src/document-loaders/blobs/archive-loader.ts
  packages/github-tool/src/document-loaders/blobs/tree-loader.ts
  packages/rag/src/chunk-store/postgres/utils.test.ts
  packages/rag/src/chunk-store/postgres/utils.ts
  packages/rag/src/index.ts
  packages/rag/src/utils/index.ts
  packages/rag/src/utils/text.test.ts
  packages/rag/src/utils/text.ts
Labels: Review effort 2/5

#1915 Add document vector store icon across workflow UI
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  internal-packages/workflow-designer-ui/src/icons/node/document-vector-store-icon.tsx
  internal-packages/workflow-designer-ui/src/icons/node/index.tsx
Labels: Review effort 1/5

#1916 refactor: Extract reusable GitHub setup badge component
  internal-packages/workflow-designer-ui/src/editor/node/ui/github-node-info.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/index.ts
  internal-packages/workflow-designer-ui/src/editor/node/ui/requires-setup-badge.tsx
Labels: Review effort 1/5

#1917 feat: add document vector store UI support
  internal-packages/workflow-designer-ui/src/editor/hooks/use-document-vector-stores.ts
  internal-packages/workflow-designer-ui/src/editor/node/node.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/document-node-info.tsx
  internal-packages/workflow-designer-ui/src/editor/node/ui/index.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/document/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/vector-store/index.tsx
Labels: Review effort 3/5

#1920 feat: Improve query panel document store display
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
Labels: Review effort 2/5

#1926 chore/v3x-1-settings-text-inverse
  apps/studio.giselles.ai/app/(main)/settings/account/user-teams.tsx
  apps/studio.giselles.ai/app/(main)/settings/components/field.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/components/agent-time-usage.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/invitation-list-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/team-members-list-item.tsx
Labels: Review effort 2/5

#1927 chore/v3x-2-apps-text-inverse
  apps/studio.giselles.ai/app/(main)/apps/components/searchable-agent-list.tsx
Labels: Review effort 1/5

#1928 chore/v3x-3-ui-buttons
  internal-packages/ui/components/button.tsx
  internal-packages/workflow-designer-ui/src/ui/button.tsx
Labels: Review effort 1/5

#1929 chore(svg): use currentColor in GoogleWhiteIcon (Phase 3 v3.x-4)
  internal-packages/workflow-designer-ui/src/icons/google.tsx
Labels: Review effort 1/5

#1924 Add document vector store query flow with metadata schema
  apps/studio.giselles.ai/lib/vector-stores/document/query/context.ts
  apps/studio.giselles.ai/lib/vector-stores/document/query/resolve-document-vector-store.ts
  apps/studio.giselles.ai/lib/vector-stores/document/query/schema.test.ts
  apps/studio.giselles.ai/lib/vector-stores/document/query/schema.ts
  apps/studio.giselles.ai/lib/vector-stores/document/query/service.test.ts
  apps/studio.giselles.ai/lib/vector-stores/document/query/service.ts
Labels: Review effort 2/5

#1855 Sanitize generation usage before persisting
  packages/giselle/src/engine/generations/internal/sanitize-usage.test.ts
  packages/giselle/src/engine/generations/internal/sanitize-usage.ts
  packages/giselle/src/engine/generations/internal/use-generation-executor.ts
Labels: Review effort 2/5

#1936 chore(settings): replace bg-/border-* (white/black) with semantic aliases in repository registration dialog (Phase 3)
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-registration-dialog.tsx
Labels: Review effort 2/5

#1937 chore(settings): replace white/black bg-/border-* with semantic/alias…
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-item.tsx
Labels: Review effort 1/5

#1938 chore(settings): replace white/black borders and surfaces with semantic/aliases in team members item (Phase 3)
  apps/studio.giselles.ai/app/(main)/settings/team/team-members-list-item.tsx
Labels: Review effort 1/5

#1939 chore(settings): move white/black bg-/border-* to semantic/aliases (invite-member-dialog, user-teams) — Phase 3
  apps/studio.giselles.ai/app/(main)/settings/account/user-teams.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/agent-usage-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/agent-usage-table.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/invitation-list-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/invite-member-dialog.tsx
Labels: Review effort 1/5

#1933 ci: upload color report artifact; docs: add Tailwind v4 verification
  .github/workflows/ci.yml
  docs/tailwind-v4-verification.md
Labels: Review effort 2/5

#1940 Integrate document vector store with query node
  apps/studio.giselles.ai/app/giselle-engine.ts
  internal-packages/workflow-designer-ui/src/ui/query-result-view.tsx
  packages/giselle/src/concepts/generation/output.ts
  packages/giselle/src/engine/operations/execute-query.ts
  packages/giselle/src/engine/types.ts
Labels: Review effort 3/5

#1943 chore(apps): unify dark bg/border to aliases in apps/(main)
  apps/studio.giselles.ai/app/(main)/apps/components/agent-card.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/search-header.tsx
  apps/studio.giselles.ai/app/(main)/apps/components/searchable-agent-list.tsx
  apps/studio.giselles.ai/app/(main)/apps/layout.tsx
  apps/studio.giselles.ai/app/(main)/apps/myapps/page.tsx
  apps/studio.giselles.ai/app/(main)/layout.tsx
  internal-packages/ui/style.css
Labels: Review effort 2/5

#1947 refactor: remove `experimental_github-webhook` route
  packages/giselle/src/next/next-giselle-engine.ts
Labels: Review effort 1/5

#1948 chore: apps(main) aliases batch 2 + stage background/border unification
  apps/studio.giselles.ai/app/(main)/apps/components/search-header.tsx
  apps/studio.giselles.ai/app/(main)/apps/layout.tsx
  apps/studio.giselles.ai/app/(main)/layout.tsx
  apps/studio.giselles.ai/app/(main)/nav.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/layout.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/user-teams.tsx
  apps/studio.giselles.ai/app/stage/(top)/circular-carousel.tsx
  apps/studio.giselles.ai/app/stage/(top)/form-input-renderer.tsx
  apps/studio.giselles.ai/app/stage/(top)/form.tsx
  apps/studio.giselles.ai/app/stage/(top)/page.tsx
  apps/studio.giselles.ai/app/stage/(top)/settings-dialog.tsx
  apps/studio.giselles.ai/app/stage/(top)/team-card.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/[stepId]/ui/step-layout.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/layout.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/mobile-actions.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/sidebar.tsx
  apps/studio.giselles.ai/app/stage/acts/components/filterable-acts-list.tsx
  apps/studio.giselles.ai/app/stage/error.tsx
  apps/studio.giselles.ai/app/stage/layout.tsx
  apps/studio.giselles.ai/app/stage/loading.tsx
  apps/studio.giselles.ai/app/stage/not-found.tsx
  apps/studio.giselles.ai/app/stage/showcase/[appId]/app-detail-client.tsx
  apps/studio.giselles.ai/app/stage/showcase/[appId]/components/run-modal.tsx
  apps/studio.giselles.ai/app/stage/showcase/playlist/[id]/playlist-detail-client.tsx
  apps/studio.giselles.ai/app/stage/showcase/showcase-client.tsx
  apps/studio.giselles.ai/app/stage/ui/mobile-header.tsx
  apps/studio.giselles.ai/app/stage/ui/navigation-rail/navigation-rail.tsx
Labels: Review effort 2/5

#1950 feat(apps): v3x bg/border aliases - apps batch 2 (glass alignment)
  apps/studio.giselles.ai/app/(main)/apps/components/search-header.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/authentication/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/general/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/account/layout.tsx
  apps/studio.giselles.ai/app/(main)/settings/layout.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/agent-usage-table.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/invitation-list-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/invite-member-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/layout.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/document/document-vector-store-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/document/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-registration-dialog.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/status-cards.tsx
Labels: Review effort 2/5

#1903 fix: Align PR comment trigger payload names with pull request fields
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/github-trigger-properties-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/utils/trigger-configuration.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/trigger-node-properties-panel/providers/github-trigger/utils/use-trigger-configuration.ts
  internal-packages/workflow-designer-ui/src/editor/v2/components/trigger-input-dialog/helpers.ts
  packages/flow/src/trigger/github.ts
  packages/flow/src/trigger/index.ts
Labels: Review effort 2/5
