Repository giselles-ai/giselle, pull requests merged in 2025-09, with the labels that each got.

#1778 feat-unify-generation-error-tracing
  apps/studio.giselles.ai/app/giselle-engine.ts
  packages/giselle/src/engine/generations/generate-text.ts
  packages/giselle/src/engine/types.ts
  packages/langfuse/src/trace-generation.ts
Labels: Review effort 3/5

#1781 fix: allow workspace access for all user's teams
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  apps/studio.giselles.ai/services/teams/fetch-workspace-team.ts
  apps/studio.giselles.ai/services/teams/index.ts
  apps/studio.giselles.ai/services/teams/is-member-of-team.ts
Labels: Review effort 2/5, Possible security concern

#1784 Remove custom maxSize limit for Image File Node
  internal-packages/workflow-designer-ui/src/editor/properties-panel/file-node-properties-panel/index.tsx
Labels: Review effort 1/5

#1785 remove: disable Perplexity AI models from playground and studio apps
  apps/playground/giselle-engine.ts
  apps/studio.giselles.ai/app/giselle-engine.ts
  apps/studio.giselles.ai/app/stage/acts/[actId]/[stepId]/page.tsx
Labels: Review effort 2/5

#1790 Update ai and @ai-sdk/* packages to latest versions
  docs/packages-license.md
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 2/5

#1777 Proofreading: Vector Stores for code/pull requests
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/diagnostic-modal.tsx
Labels: Review effort 1/5

#1669 feat: allow updating GitHub credentials without resetting tool selections
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/github/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/tool-provider/use-tool-provider-connection.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/tools/ui/tool-configuration-dialog.tsx
Labels: Review effort 2/5, Review effort 3/5

#1794 feat(giselle): move workspace fetch app and wrap children with workflow provider
  apps/studio.giselles.ai/app/workspaces/[workspaceId]/layout.tsx
  packages/giselle/src/react/workspace/provider.tsx
Labels: Review effort 3/5

#1798 chore: remove Claude Code GitHub workflow
  .github/workflows/claudecode.yml
Labels: Review effort 1/5

#1811 fix(showcase): add missing required parameters to startAct call
  apps/studio.giselles.ai/app/stage/showcase/[appId]/actions.ts
Labels: Review effort 1/5

#1815 perf-log-text-generation-timing
  packages/giselle/src/engine/generations/generate-text.ts
  packages/giselle/src/engine/generations/internal/use-generation-executor.ts
Labels: Review effort 2/5, Possible security concern

#1813 feat: add Sentry user identification for authenticated users
  apps/studio.giselles.ai/app/(main)/layout.tsx
  apps/studio.giselles.ai/components/sentry-user-provider.tsx
  apps/studio.giselles.ai/components/sentry-user-wrapper.tsx
Labels: Review effort 2/5

#1832 feat(ui): incremental rename on duplicate for pasted/dragged/selected images
  internal-packages/workflow-designer-ui/src/editor/properties-panel/file-node-properties-panel/file-panel.tsx
Labels: Review effort 2/5

#1834 fix(security): prevent open redirect in OAuth callback
  apps/studio.giselles.ai/app/(auth)/auth/callback/[provider]/route.ts
Labels: Review effort 2/5, Possible security concern

#1838 feat(studio): add sidebar navigation for vector stores
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/document/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/navigation-layout.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/sidebar-menu.tsx
Labels: Review effort 2/5

#1848 fix: Validate non-empty prompt before text/image generation
  internal-packages/workflow-designer-ui/src/editor/lib/validate-prompt.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx
Labels: Review effort 2/5

#1844 feat(studio): add database schema for document vector stores
  apps/studio.giselles.ai/drizzle/schema.ts
  apps/studio.giselles.ai/migrations/0048_useful_the_phantom.sql
  apps/studio.giselles.ai/migrations/meta/0048_snapshot.json
  apps/studio.giselles.ai/migrations/meta/_journal.json
  apps/studio.giselles.ai/packages/types.ts
Labels: Review effort 2/5

#1846 feat: support image editing for nano banana
  internal-packages/workflow-designer-ui/src/editor/connector/component.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/index.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/input-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/sources/use-connected-sources.ts
  internal-packages/workflow-designer-ui/src/editor/tool/toolbar/toolbar.tsx
  packages/giselle/src/concepts/generation/output.ts
  packages/giselle/src/engine/generations/generate-image.ts
  packages/giselle/src/engine/generations/generate-text.ts
  packages/giselle/src/engine/generations/internal/use-generation-executor.ts
  packages/giselle/src/engine/generations/utils.ts
  packages/giselle/src/react/flow/utils/is-supported-connection.test.ts
  packages/giselle/src/react/flow/utils/is-supported-connection.ts
  packages/language-model/src/base.ts
  packages/language-model/src/google-image.ts
  packages/text-editor/src/react/source-extension-react.tsx
Labels: Review effort 3/5

#1841 feat: add tool step limit for text generation with GPT-5 models exception
  packages/giselle/src/engine/generations/generate-text.ts
Labels: Review effort 2/5

#1856 Redesign text generation pipeline with durable execution process (beyond 800s limit)
  apps/studio.giselles.ai/app/giselle-engine.ts
  docs/packages-license.md
  packages/giselle/package.json
  packages/giselle/src/concepts/path.ts
  packages/giselle/src/engine/experimental_storage/fs-storage-driver.ts
  packages/giselle/src/engine/experimental_storage/memory-storage-driver.ts
  packages/giselle/src/engine/experimental_storage/types.ts
  packages/giselle/src/engine/generations/generate-content.ts
  packages/giselle/src/engine/generations/get-generation-message-chunks.ts
  packages/giselle/src/engine/generations/index.ts
  packages/giselle/src/engine/generations/internal/use-generation-executor.ts
  packages/giselle/src/engine/generations/start-content-generation.ts
  packages/giselle/src/engine/index.ts
  packages/giselle/src/engine/types.ts
  packages/giselle/src/http/router.ts
  packages/giselle/src/react/generations/generate-content-runner.tsx
  packages/giselle/src/react/generations/generation-runner.tsx
  packages/giselle/src/react/generations/store.ts
  packages/giselle/src/utils/batch.ts
  packages/giselle/src/utils/index.ts
  packages/supabase-driver/src/storage/supabase-storage-driver.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 4/5

#1862 feat(generation): new text generation api cancelable
  packages/giselle/src/engine/generations/generate-content.ts
  packages/giselle/src/react/generations/contexts/generation-runner-system.tsx
  packages/giselle/src/react/generations/generate-content-runner.tsx
  packages/giselle/src/react/generations/generation-runner.tsx
  packages/giselle/src/react/generations/hooks/use-node-generations.ts
  packages/giselle/src/react/generations/zustand-bridge-generation-provider.tsx
Labels: Review effort 2/5

#1849 feat(studio): implement document vector store persistence and management UI
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/data.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/document-vector-store-list.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/document/page.tsx
Labels: Review effort 2/5, Review effort 3/5

#1870 fix: prompt references missing immediately after connecting inputs
  internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/prompt-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/query-node-properties-panel/query-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/prompt-panel.tsx
Labels: Review effort 2/5

#1861 feat(studio): add configuration dialog for document vector stores
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/actions.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/data.ts
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/document-vector-store-list.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/document/document-vector-store-item.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/document/page.tsx
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/types.ts
Labels: Review effort 3/5

#1865 feat(studio): add PDF document upload to document vector stores
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/document/document-vector-store-item.tsx
  apps/studio.giselles.ai/app/api/vector-stores/document/[documentVectorStoreId]/documents/route.ts
  apps/studio.giselles.ai/lib/vector-stores/document/constants.ts
  apps/studio.giselles.ai/lib/vector-stores/document/utils.ts
Labels: Review effort 3/5, Possible security concern

#1880 feat: add GPT-5-codex model to existing GPT-5 series
  packages/language-model/src/costs/index.test.ts
  packages/language-model/src/costs/model-prices.ts
  packages/language-model/src/openai.test.ts
  packages/language-model/src/openai.ts
Labels: Review effort 2/5

#1876 Create shared URL validation helper for Workflow Designer UI
  internal-packages/workflow-designer-ui/src/editor/chat/chat-panel.tsx
  internal-packages/workflow-designer-ui/src/editor/lib/validate-url.ts
  internal-packages/workflow-designer-ui/src/editor/properties-panel/web-page-node-properties-panel/index.tsx
Labels: Review effort 2/5

#1881 feat: add Cohere embed-4 multimodal embedding cost calculation support
  packages/langfuse/src/trace-embedding.ts
  packages/language-model/src/costs/embedding-costs.test.ts
  packages/language-model/src/costs/index.ts
  packages/language-model/src/costs/model-prices.ts
  packages/rag/README.md
  packages/rag/src/embedder/ai-sdk-embedder.test.ts
  packages/rag/src/embedder/ai-sdk-embedder.ts
  packages/rag/src/embedder/types.ts
Labels: Review effort 2/5

#1882 fix: Improve Vector Store Dropdown and GitHub Action Installed Panel Scrolling
  apps/studio.giselles.ai/app/(main)/settings/team/vector-stores/repository-registration-dialog.tsx
  internal-packages/workflow-designer-ui/src/editor/properties-panel/action-node-properties-panel/github-action-properties-panel.tsx
Labels: Review effort 2/5

#1867 chore(colors): foundation v2 – tokens.css + aliases.css (non-breaking)
  internal-packages/ui/style.css
  internal-packages/ui/styles/aliases.css
  internal-packages/ui/styles/tokens.css
Labels: Review effort 2/5

#1868 chore(colors): foundation v3 - stage: replace text-white-900 with text-inverse; add codemods
  apps/studio.giselles.ai/app/stage/(top)/form-input-renderer.tsx
  apps/studio.giselles.ai/app/stage/(top)/form.tsx
  apps/studio.giselles.ai/app/stage/(top)/team-card.tsx
  apps/studio.giselles.ai/app/stage/acts/[actId]/ui/sidebar.tsx
  apps/studio.giselles.ai/app/stage/acts/components/filterable-acts-list.tsx
  apps/studio.giselles.ai/app/stage/ui/mobile-header.tsx
  package.json
  scripts/codemods/replace-text-black-600-20.mjs
  scripts/codemods/replace-text-white-900-to-inverse.mjs
Labels: Review effort 2/5

#1872 fix: Add PR diff support for GitHub trigger PR closed
  internal-packages/workflow-designer-ui/src/editor/v2/components/trigger-input-dialog/helpers.ts
  packages/flow/src/trigger/github.ts
  packages/giselle/src/engine/github/trigger-utils.test.ts
  packages/giselle/src/engine/github/trigger-utils.ts
Labels: Review effort 2/5

#1888 fix(giselle): always run tracing and skip trigger.dev only for delegated cases
  apps/studio.giselles.ai/app/giselle-engine.ts
Labels: Review effort 2/5

#1886 feat: add runner syncing, simplify generation selection and stream handling
  packages/giselle/src/react/generations/generate-content-runner.tsx
  packages/giselle/src/react/generations/hooks/use-node-generations.ts
  packages/giselle/src/react/generations/store.ts
Labels: Review effort 3/5
